
package it.webred.AMProfiler.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;

import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Tue Oct 07 16:06:15 CEST 2014
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "sayHello", namespace = "http://services.AMProfiler.webred.it/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHello", namespace = "http://services.AMProfiler.webred.it/")

public class SayHello {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }//-------------------------------------------------------------------------

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }//-------------------------------------------------------------------------

}

