SELECT pers.CODFISC AS CODICE_FISCALE
  FROM  MVW_SUC_STO_STACIV staciv, SIT_D_PERSONA pers 
 WHERE staciv.CODICE_FISCALE  = ?
   AND pers.ID_ORIG  = lpad(staciv.MATRICOLA_CONIUGE,10,'0')
   AND DT_FINE_VAL IS NULL
   AND STACIV.PER_STATO_CIVILE = 'C'
