--TABELLA PRATICA DI DEPOSITO DELLA PLANIMETRIA
ALTER TABLE VIRGILIO.S_C340_PRAT_DEPOSITO_PLANIM
 DROP PRIMARY KEY CASCADE;
DROP TABLE VIRGILIO.S_C340_PRAT_DEPOSITO_PLANIM CASCADE CONSTRAINTS;

CREATE TABLE VIRGILIO.S_C340_PRAT_DEPOSITO_PLANIM
(
  ID                   NUMBER(20),
  ID_UIU               NUMBER(20)               NOT NULL,
  COMUNE_PRES_PRATICA  VARCHAR2(4 BYTE),
  DATA_PRES_PRATICA    DATE,
  COGNOME_DICH         VARCHAR2(200 BYTE),
  NOME_DICH            VARCHAR2(50 BYTE),
  CF_DICH              VARCHAR2(16 BYTE),
  VIA_DICH             VARCHAR2(70 BYTE),
  CIVICO_DICH          VARCHAR2(11 BYTE),
  TELEFONO_DICH        VARCHAR2(15 BYTE),
  TITOLO_DICH          VARCHAR2(50 BYTE),
  DENOM_ENTE           VARCHAR2(2000 BYTE),
  PIVA_ENTE            VARCHAR2(11 BYTE),
  VIA_ENTE             VARCHAR2(70 BYTE),
  CIVICO_ENTE          VARCHAR2(11 BYTE),
  TELEFONO_ENTE        VARCHAR2(15 BYTE),
  TITOLO_ENTE          VARCHAR2(50 BYTE),
  COMUNE_UIU           VARCHAR2(4 BYTE),
  VIA_UIU              VARCHAR2(70 BYTE),
  CIVICO_UIU           VARCHAR2(11 BYTE),
  COMUNE_NCEU          VARCHAR2(4 BYTE),
  SEZIONE              VARCHAR2(3 BYTE),
  FOGLIO               NUMBER(4),
  PARTICELLA           NUMBER(5),
  UNIMM                NUMBER(5),
  PROT_RICHIESTA       VARCHAR2(9 BYTE),
  DATA_RICHIESTA       DATE,
  PROT_DENUNCIA        VARCHAR2(9 BYTE),
  DATA_DENUNCIA        DATE,
  COMUNE_DICH          VARCHAR2(4 BYTE),
  COMUNE_ENTE          VARCHAR2(4 BYTE),
  DATA_ULT_MODIFICA    DATE
)
TABLESPACE MILANO
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE VIRGILIO.S_C340_PRAT_DEPOSITO_PLANIM ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE MILANO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


--TABELLA PRATICA DI RETTIFICA DELLA SUPERFICIE
ALTER TABLE VIRGILIO.S_C340_PRAT_RETTIFICA_SUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE VIRGILIO.S_C340_PRAT_RETTIFICA_SUP CASCADE CONSTRAINTS;

CREATE TABLE VIRGILIO.S_C340_PRAT_RETTIFICA_SUP
(
  ID                   NUMBER(20),
  ID_UIU               NUMBER(20)               NOT NULL,
  COMUNE_PRES_PRATICA  VARCHAR2(4 BYTE),
  DATA_PRES_PRATICA    DATE,
  COGNOME_DICH         VARCHAR2(200 BYTE),
  NOME_DICH            VARCHAR2(50 BYTE),
  CF_DICH              VARCHAR2(16 BYTE),
  VIA_DICH             VARCHAR2(70 BYTE),
  CIVICO_DICH          VARCHAR2(11 BYTE),
  TELEFONO_DICH        VARCHAR2(15 BYTE),
  TITOLO_DICH          VARCHAR2(50 BYTE),
  DENOM_ENTE           VARCHAR2(2000 BYTE),
  PIVA_ENTE            VARCHAR2(11 BYTE),
  VIA_ENTE             VARCHAR2(70 BYTE),
  CIVICO_ENTE          VARCHAR2(11 BYTE),
  TELEFONO_ENTE        VARCHAR2(15 BYTE),
  TITOLO_ENTE          VARCHAR2(50 BYTE),
  COMUNE_UIU           VARCHAR2(4 BYTE),
  VIA_UIU              VARCHAR2(70 BYTE),
  CIVICO_UIU           VARCHAR2(11 BYTE),
  COMUNE_NCEU          VARCHAR2(4 BYTE),
  SEZIONE              VARCHAR2(3 BYTE),
  FOGLIO               NUMBER(4),
  PARTICELLA           NUMBER(5),
  UNIMM                NUMBER(5),
  PROT_RICHIESTA       VARCHAR2(9 BYTE),
  DATA_RICHIESTA       DATE,
  MQ_INIZIALI          NUMBER(10,2)             NOT NULL,
  MQ_FINALI            NUMBER(10,2)             NOT NULL,
  COMUNE_ENTE          VARCHAR2(4 BYTE),
  COMUNE_DICH          VARCHAR2(4 BYTE),
  DATA_ULT_MODIFICA    DATE
)
TABLESPACE MILANO
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE VIRGILIO.S_C340_PRAT_RETTIFICA_SUP ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE MILANO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));



-- TABELLA ALLEGATI PRATICHE
ALTER TABLE VIRGILIO.S_C340_PRAT_ALLEGATO
 DROP PRIMARY KEY CASCADE;
DROP TABLE VIRGILIO.S_C340_PRAT_ALLEGATO CASCADE CONSTRAINTS;

CREATE TABLE VIRGILIO.S_C340_PRAT_ALLEGATO
(
  ID              NUMBER(20),
  ID_PRATICA      NUMBER(20)                    NOT NULL,
  NOME_FILE       VARCHAR2(2000 BYTE)           NOT NULL,
  DATA_CREAZIONE  DATE
)
TABLESPACE MILANO
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX VIRGILIO.S_C340_PRAT_ALLEGATO_PK ON VIRGILIO.S_C340_PRAT_ALLEGATO
(ID)
LOGGING
TABLESPACE MILANO
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE VIRGILIO.S_C340_PRAT_ALLEGATO ADD (
  CONSTRAINT S_C340_PRAT_ALLEGATO_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE MILANO
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

