DROP SYNONYM DIOGENE.CONS_URUI_TAB;

CREATE SYNONYM DIOGENE.CONS_URUI_TAB FOR SITI_F205.CONS_URUI_TAB;

DROP SYNONYM DIOGENE.load_cat_uiu_id;

CREATE SYNONYM DIOGENE.load_cat_uiu_id FOR SITI_F205.load_cat_uiu_id;





