package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.35 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * AmApplicationItem generated by hbm2java
 */

public class AmApplicationItem  implements java.io.Serializable {


    // Fields    

     private Long id;
     private AmApplication amApplication;
     private AmItem amItem;
     private Set amItemRoles = new HashSet(0);


    // Constructors

    /** default constructor */
    public AmApplicationItem() {
    }

	/** minimal constructor */
    public AmApplicationItem(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public AmApplicationItem(Long id, AmApplication amApplication, AmItem amItem, Set amItemRoles) {
        this.id = id;
        this.amApplication = amApplication;
        this.amItem = amItem;
        this.amItemRoles = amItemRoles;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public AmApplication getAmApplication() {
        return this.amApplication;
    }
    
    public void setAmApplication(AmApplication amApplication) {
        this.amApplication = amApplication;
    }

    public AmItem getAmItem() {
        return this.amItem;
    }
    
    public void setAmItem(AmItem amItem) {
        this.amItem = amItem;
    }

    public Set getAmItemRoles() {
        return this.amItemRoles;
    }
    
    public void setAmItemRoles(Set amItemRoles) {
        this.amItemRoles = amItemRoles;
    }
   








}
