package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.36 by Hibernate Tools 3.1.0.beta4



/**
 * AmComuniId generated by hbm2java
 */

public class AmComuniId  implements java.io.Serializable {


    // Fields    

     private String belfiore;
     private String descrizione;


    // Constructors

    /** default constructor */
    public AmComuniId() {
    }

    
    /** full constructor */
    public AmComuniId(String belfiore, String descrizione) {
        this.belfiore = belfiore;
        this.descrizione = descrizione;
    }
    

   
    // Property accessors

    public String getBelfiore() {
        return this.belfiore;
    }
    
    public void setBelfiore(String belfiore) {
        this.belfiore = belfiore;
    }

    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmComuniId) ) return false;
		 AmComuniId castOther = ( AmComuniId ) other; 
         
		 return ( (this.getBelfiore()==castOther.getBelfiore()) || ( this.getBelfiore()!=null && castOther.getBelfiore()!=null && this.getBelfiore().equals(castOther.getBelfiore()) ) )
 && ( (this.getDescrizione()==castOther.getDescrizione()) || ( this.getDescrizione()!=null && castOther.getDescrizione()!=null && this.getDescrizione().equals(castOther.getDescrizione()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBelfiore() == null ? 0 : this.getBelfiore().hashCode() );
         result = 37 * result + ( getDescrizione() == null ? 0 : this.getDescrizione().hashCode() );
         return result;
   }   





}
