package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.36 by Hibernate Tools 3.1.0.beta4



/**
 * AmComuni generated by hbm2java
 */

public class AmComuni  implements java.io.Serializable {


    // Fields    

     private AmComuniId id;


    // Constructors

    /** default constructor */
    public AmComuni() {
    }

    
    /** full constructor */
    public AmComuni(AmComuniId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public AmComuniId getId() {
        return this.id;
    }
    
    public void setId(AmComuniId id) {
        this.id = id;
    }
   








}
