package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.35 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * AmItem generated by hbm2java
 */

public class AmItem  implements java.io.Serializable {


    // Fields    

     private String name;
     private Set amPermissions = new HashSet(0);
     private Set amApplicationItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public AmItem() {
    }

	/** minimal constructor */
    public AmItem(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public AmItem(String name, Set amPermissions, Set amApplicationItems) {
        this.name = name;
        this.amPermissions = amPermissions;
        this.amApplicationItems = amApplicationItems;
    }
    

   
    // Property accessors

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getAmPermissions() {
        return this.amPermissions;
    }
    
    public void setAmPermissions(Set amPermissions) {
        this.amPermissions = amPermissions;
    }

    public Set getAmApplicationItems() {
        return this.amApplicationItems;
    }
    
    public void setAmApplicationItems(Set amApplicationItems) {
        this.amApplicationItems = amApplicationItems;
    }
   








}
