package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.35 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * AmItemRole generated by hbm2java
 */

public class AmItemRole  implements java.io.Serializable {


    // Fields    

     private Long id;
     private AmRole amRole;
     private AmApplicationItem amApplicationItem;
     private Set amUserIrs = new HashSet(0);
     private Set amRolePermissions = new HashSet(0);


    // Constructors

    /** default constructor */
    public AmItemRole() {
    }

	/** minimal constructor */
    public AmItemRole(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public AmItemRole(Long id, AmRole amRole, AmApplicationItem amApplicationItem, Set amUserIrs, Set amRolePermissions) {
        this.id = id;
        this.amRole = amRole;
        this.amApplicationItem = amApplicationItem;
        this.amUserIrs = amUserIrs;
        this.amRolePermissions = amRolePermissions;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public AmRole getAmRole() {
        return this.amRole;
    }
    
    public void setAmRole(AmRole amRole) {
        this.amRole = amRole;
    }

    public AmApplicationItem getAmApplicationItem() {
        return this.amApplicationItem;
    }
    
    public void setAmApplicationItem(AmApplicationItem amApplicationItem) {
        this.amApplicationItem = amApplicationItem;
    }

    public Set getAmUserIrs() {
        return this.amUserIrs;
    }
    
    public void setAmUserIrs(Set amUserIrs) {
        this.amUserIrs = amUserIrs;
    }

    public Set getAmRolePermissions() {
        return this.amRolePermissions;
    }
    
    public void setAmRolePermissions(Set amRolePermissions) {
        this.amRolePermissions = amRolePermissions;
    }
   








}
