package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.35 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * AmPermission generated by hbm2java
 */

public class AmPermission  implements java.io.Serializable {


    // Fields    

     private String permission;
     private AmItem amItem;
     private Set amRolePermissions = new HashSet(0);


    // Constructors

    /** default constructor */
    public AmPermission() {
    }

	/** minimal constructor */
    public AmPermission(String permission, AmItem amItem) {
        this.permission = permission;
        this.amItem = amItem;
    }
    
    /** full constructor */
    public AmPermission(String permission, AmItem amItem, Set amRolePermissions) {
        this.permission = permission;
        this.amItem = amItem;
        this.amRolePermissions = amRolePermissions;
    }
    

   
    // Property accessors

    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }

    public AmItem getAmItem() {
        return this.amItem;
    }
    
    public void setAmItem(AmItem amItem) {
        this.amItem = amItem;
    }

    public Set getAmRolePermissions() {
        return this.amRolePermissions;
    }
    
    public void setAmRolePermissions(Set amRolePermissions) {
        this.amRolePermissions = amRolePermissions;
    }
   








}
