package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.36 by Hibernate Tools 3.1.0.beta4



/**
 * AmRolePermissionId generated by hbm2java
 */

public class AmRolePermissionId  implements java.io.Serializable {


    // Fields    

     private long fkAmItemRole;
     private String fkAmPermission;


    // Constructors

    /** default constructor */
    public AmRolePermissionId() {
    }

    
    /** full constructor */
    public AmRolePermissionId(long fkAmItemRole, String fkAmPermission) {
        this.fkAmItemRole = fkAmItemRole;
        this.fkAmPermission = fkAmPermission;
    }
    

   
    // Property accessors

    public long getFkAmItemRole() {
        return this.fkAmItemRole;
    }
    
    public void setFkAmItemRole(long fkAmItemRole) {
        this.fkAmItemRole = fkAmItemRole;
    }

    public String getFkAmPermission() {
        return this.fkAmPermission;
    }
    
    public void setFkAmPermission(String fkAmPermission) {
        this.fkAmPermission = fkAmPermission;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmRolePermissionId) ) return false;
		 AmRolePermissionId castOther = ( AmRolePermissionId ) other; 
         
		 return (this.getFkAmItemRole()==castOther.getFkAmItemRole())
 && ( (this.getFkAmPermission()==castOther.getFkAmPermission()) || ( this.getFkAmPermission()!=null && castOther.getFkAmPermission()!=null && this.getFkAmPermission().equals(castOther.getFkAmPermission()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getFkAmItemRole();
         result = 37 * result + ( getFkAmPermission() == null ? 0 : this.getFkAmPermission().hashCode() );
         return result;
   }   





}
