package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.35 by Hibernate Tools 3.1.0.beta4



/**
 * AmUserIr generated by hbm2java
 */

public class AmUserIr  implements java.io.Serializable {


    // Fields    

     private AmUserIrId id;
     private AmItemRole amItemRole;
     private AmUser amUser;


    // Constructors

    /** default constructor */
    public AmUserIr() {
    }

	/** minimal constructor */
    public AmUserIr(AmUserIrId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AmUserIr(AmUserIrId id, AmItemRole amItemRole, AmUser amUser) {
        this.id = id;
        this.amItemRole = amItemRole;
        this.amUser = amUser;
    }
    

   
    // Property accessors

    public AmUserIrId getId() {
        return this.id;
    }
    
    public void setId(AmUserIrId id) {
        this.id = id;
    }

    public AmItemRole getAmItemRole() {
        return this.amItemRole;
    }
    
    public void setAmItemRole(AmItemRole amItemRole) {
        this.amItemRole = amItemRole;
    }

    public AmUser getAmUser() {
        return this.amUser;
    }
    
    public void setAmUser(AmUser amUser) {
        this.amUser = amUser;
    }
   








}
