package it.webred.diogene.db.model.am;
// Generated 22-nov-2007 11.42.35 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AmUser generated by hbm2java
 */

public class AmUser  implements java.io.Serializable {


    // Fields    

     private String name;
     private String pwd;
     private Date dtIns;
     private String userIns;
     private Date lastAccess;
     private String disableCause;
     private Set amUserIrs = new HashSet(0);


    // Constructors

    /** default constructor */
    public AmUser() {
    }

	/** minimal constructor */
    public AmUser(String name, Date dtIns, String userIns) {
        this.name = name;
        this.dtIns = dtIns;
        this.userIns = userIns;
    }
    
    /** full constructor */
    public AmUser(String name, String pwd, Date dtIns, String userIns, Date lastAccess, String disableCause, Set amUserIrs) {
        this.name = name;
        this.pwd = pwd;
        this.dtIns = dtIns;
        this.userIns = userIns;
        this.lastAccess = lastAccess;
        this.disableCause = disableCause;
        this.amUserIrs = amUserIrs;
    }
    

   
    // Property accessors

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Date getDtIns() {
        return this.dtIns;
    }
    
    public void setDtIns(Date dtIns) {
        this.dtIns = dtIns;
    }

    public String getUserIns() {
        return this.userIns;
    }
    
    public void setUserIns(String userIns) {
        this.userIns = userIns;
    }

    public Date getLastAccess() {
        return this.lastAccess;
    }
    
    public void setLastAccess(Date lastAccess) {
        this.lastAccess = lastAccess;
    }

    public String getDisableCause() {
        return this.disableCause;
    }
    
    public void setDisableCause(String disableCause) {
        this.disableCause = disableCause;
    }

    public Set getAmUserIrs() {
        return this.amUserIrs;
    }
    
    public void setAmUserIrs(Set amUserIrs) {
        this.amUserIrs = amUserIrs;
    }
   








}
