select 'MSCVNC71E44F205R' as CODICE_FISCALE,50 as PERC_POSS from dual
where 
DECODE(?,NULL,NULL,NULL) IS NULL
AND DECODE(?,NULL,NULL,NULL) IS NULL
AND DECODE(?,NULL,NULL,NULL) IS NULL
AND DECODE(?,NULL,NULL,NULL) IS NULL
