package it.webred.docfa.model;
// Generated 1-apr-2009 13.23.55 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * DocfaDapBase generated by hbm2java
 */

public class DocfaDapBase  implements java.io.Serializable {


    // Fields    

     private long iid;
     private String iidFornitura;
     private String iidProtocolloReg;
     private String idSoggetto;
     private String tipoSoggetto;
     private String foglio;
     private String particella;
     private String subalterno;
     private String tipoImmobile;
     private BigDecimal dapImporto;
     private Integer dapMesi;
     private Boolean flagDapDiritto;
     private Integer dapNumeroSoggetti;
     private String dapData;
     private String esitoDap;
     private Boolean flagSkipped;


    // Constructors

    /** default constructor */
    public DocfaDapBase() {
    }

    
    /** full constructor */
    public DocfaDapBase(String iidFornitura, String iidProtocolloReg, String idSoggetto, String tipoSoggetto, String foglio, String particella, String subalterno, String tipoImmobile, BigDecimal dapImporto, Integer dapMesi, Boolean flagDapDiritto, Integer dapNumeroSoggetti, String dapData, String esitoDap, Boolean flagSkipped) {
        this.iidFornitura = iidFornitura;
        this.iidProtocolloReg = iidProtocolloReg;
        this.idSoggetto = idSoggetto;
        this.tipoSoggetto = tipoSoggetto;
        this.foglio = foglio;
        this.particella = particella;
        this.subalterno = subalterno;
        this.tipoImmobile = tipoImmobile;
        this.dapImporto = dapImporto;
        this.dapMesi = dapMesi;
        this.flagDapDiritto = flagDapDiritto;
        this.dapNumeroSoggetti = dapNumeroSoggetti;
        this.dapData = dapData;
        this.esitoDap = esitoDap;
        this.flagSkipped = flagSkipped;
    }
    

   
    // Property accessors

    public long getIid() {
        return this.iid;
    }
    
    public void setIid(long iid) {
        this.iid = iid;
    }

    public String getIidFornitura() {
        return this.iidFornitura;
    }
    
    public void setIidFornitura(String iidFornitura) {
        this.iidFornitura = iidFornitura;
    }

    public String getIidProtocolloReg() {
        return this.iidProtocolloReg;
    }
    
    public void setIidProtocolloReg(String iidProtocolloReg) {
        this.iidProtocolloReg = iidProtocolloReg;
    }

    public String getIdSoggetto() {
        return this.idSoggetto;
    }
    
    public void setIdSoggetto(String idSoggetto) {
        this.idSoggetto = idSoggetto;
    }

    public String getTipoSoggetto() {
        return this.tipoSoggetto;
    }
    
    public void setTipoSoggetto(String tipoSoggetto) {
        this.tipoSoggetto = tipoSoggetto;
    }

    public String getFoglio() {
        return this.foglio;
    }
    
    public void setFoglio(String foglio) {
        this.foglio = foglio;
    }

    public String getParticella() {
        return this.particella;
    }
    
    public void setParticella(String particella) {
        this.particella = particella;
    }

    public String getSubalterno() {
        return this.subalterno;
    }
    
    public void setSubalterno(String subalterno) {
        this.subalterno = subalterno;
    }

    public String getTipoImmobile() {
        return this.tipoImmobile;
    }
    
    public void setTipoImmobile(String tipoImmobile) {
        this.tipoImmobile = tipoImmobile;
    }

    public BigDecimal getDapImporto() {
        return this.dapImporto;
    }
    
    public void setDapImporto(BigDecimal dapImporto) {
        this.dapImporto = dapImporto;
    }

    public Integer getDapMesi() {
        return this.dapMesi;
    }
    
    public void setDapMesi(Integer dapMesi) {
        this.dapMesi = dapMesi;
    }

    public Boolean getFlagDapDiritto() {
        return this.flagDapDiritto;
    }
    
    public void setFlagDapDiritto(Boolean flagDapDiritto) {
        this.flagDapDiritto = flagDapDiritto;
    }

    public Integer getDapNumeroSoggetti() {
        return this.dapNumeroSoggetti;
    }
    
    public void setDapNumeroSoggetti(Integer dapNumeroSoggetti) {
        this.dapNumeroSoggetti = dapNumeroSoggetti;
    }

    public String getDapData() {
        return this.dapData;
    }
    
    public void setDapData(String dapData) {
        this.dapData = dapData;
    }

    public String getEsitoDap() {
        return this.esitoDap;
    }
    
    public void setEsitoDap(String esitoDap) {
        this.esitoDap = esitoDap;
    }

    public Boolean getFlagSkipped() {
        return this.flagSkipped;
    }
    
    public void setFlagSkipped(Boolean flagSkipped) {
        this.flagSkipped = flagSkipped;
    }
   








}
