package it.webred.docfa.model;
// Generated 1-apr-2009 13.23.58 by Hibernate Tools 3.1.0.beta4



/**
 * DocfaDapToBeExported generated by hbm2java
 */

public class DocfaDapToBeExported  implements java.io.Serializable {


    // Fields    

     private String iidFornitura;
     private String iidProtocolloReg;


    // Constructors

    /** default constructor */
    public DocfaDapToBeExported() {
    }

    
    /** full constructor */
    public DocfaDapToBeExported(String iidFornitura, String iidProtocolloReg) {
        this.iidFornitura = iidFornitura;
        this.iidProtocolloReg = iidProtocolloReg;
    }
    

   
    // Property accessors

    public String getIidFornitura() {
        return this.iidFornitura;
    }
    
    public void setIidFornitura(String iidFornitura) {
        this.iidFornitura = iidFornitura;
    }

    public String getIidProtocolloReg() {
        return this.iidProtocolloReg;
    }
    
    public void setIidProtocolloReg(String iidProtocolloReg) {
        this.iidProtocolloReg = iidProtocolloReg;
    }
   








}
