//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.01 at 10:44:17 AM CET 
//


package it.webred.ct.service.jaxb.verificaCoordinate.request;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nonResidenziale complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nonResidenziale">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categoriaEdilizia" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="A10"/>
 *               &lt;enumeration value="C1"/>
 *               &lt;enumeration value="C2"/>
 *               &lt;enumeration value="C3"/>
 *               &lt;enumeration value="C6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C6" type="{}c6" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nonResidenziale", propOrder = {
    "categoriaEdilizia",
    "c6"
})
public class NonResidenziale
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected String categoriaEdilizia;
    @XmlElement(name = "C6")
    protected C6 c6;

    /**
     * Gets the value of the categoriaEdilizia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoriaEdilizia() {
        return categoriaEdilizia;
    }

    /**
     * Sets the value of the categoriaEdilizia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoriaEdilizia(String value) {
        this.categoriaEdilizia = value;
    }

    public boolean isSetCategoriaEdilizia() {
        return (this.categoriaEdilizia!= null);
    }

    /**
     * Gets the value of the c6 property.
     * 
     * @return
     *     possible object is
     *     {@link C6 }
     *     
     */
    public C6 getC6() {
        return c6;
    }

    /**
     * Sets the value of the c6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link C6 }
     *     
     */
    public void setC6(C6 value) {
        this.c6 = value;
    }

    public boolean isSetC6() {
        return (this.c6 != null);
    }

}
