//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.01 at 10:44:17 AM CET 
//


package it.webred.ct.service.jaxb.verificaCoordinate.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.webred.ct.service.jaxb.verificaCoordinate.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.webred.ct.service.jaxb.verificaCoordinate.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Credenziali }
     * 
     */
    public Credenziali createCredenziali() {
        return new Credenziali();
    }

    /**
     * Create an instance of {@link C6 }
     * 
     */
    public C6 createC6() {
        return new C6();
    }

    /**
     * Create an instance of {@link VerificaCoordinate }
     * 
     */
    public VerificaCoordinate createVerificaCoordinate() {
        return new VerificaCoordinate();
    }

    /**
     * Create an instance of {@link NonResidenziale }
     * 
     */
    public NonResidenziale createNonResidenziale() {
        return new NonResidenziale();
    }

    /**
     * Create an instance of {@link DatiCatastali }
     * 
     */
    public DatiCatastali createDatiCatastali() {
        return new DatiCatastali();
    }

    /**
     * Create an instance of {@link DatiToponomastici }
     * 
     */
    public DatiToponomastici createDatiToponomastici() {
        return new DatiToponomastici();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link CommonUserInfo }
     * 
     */
    public CommonUserInfo createCommonUserInfo() {
        return new CommonUserInfo();
    }

    /**
     * Create an instance of {@link Residenziale }
     * 
     */
    public Residenziale createResidenziale() {
        return new Residenziale();
    }

}
