//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.01 at 10:44:17 AM CET 
//


package it.webred.ct.service.jaxb.verificaCoordinate.request;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verificaCoordinate element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="verificaCoordinate">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="infoUtente" type="{}userInfo" minOccurs="0"/>
 *           &lt;element name="credenziali" type="{}credenziali" minOccurs="0"/>
 *           &lt;element name="datiToponomastici" type="{}datiToponomastici" minOccurs="0"/>
 *           &lt;element name="datiCatastali" type="{}datiCatastali" minOccurs="0"/>
 *           &lt;element name="residenziale" type="{}residenziale" minOccurs="0"/>
 *           &lt;element name="nonResidenziale" type="{}nonResidenziale" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infoUtente",
    "credenziali",
    "datiToponomastici",
    "datiCatastali",
    "residenziale",
    "nonResidenziale"
})
@XmlRootElement(name = "verificaCoordinate")
public class VerificaCoordinate
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected UserInfo infoUtente;
    protected Credenziali credenziali;
    protected DatiToponomastici datiToponomastici;
    protected DatiCatastali datiCatastali;
    protected Residenziale residenziale;
    protected NonResidenziale nonResidenziale;

    /**
     * Gets the value of the infoUtente property.
     * 
     * @return
     *     possible object is
     *     {@link UserInfo }
     *     
     */
    public UserInfo getInfoUtente() {
        return infoUtente;
    }

    /**
     * Sets the value of the infoUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInfo }
     *     
     */
    public void setInfoUtente(UserInfo value) {
        this.infoUtente = value;
    }

    public boolean isSetInfoUtente() {
        return (this.infoUtente!= null);
    }

    /**
     * Gets the value of the credenziali property.
     * 
     * @return
     *     possible object is
     *     {@link Credenziali }
     *     
     */
    public Credenziali getCredenziali() {
        return credenziali;
    }

    /**
     * Sets the value of the credenziali property.
     * 
     * @param value
     *     allowed object is
     *     {@link Credenziali }
     *     
     */
    public void setCredenziali(Credenziali value) {
        this.credenziali = value;
    }

    public boolean isSetCredenziali() {
        return (this.credenziali!= null);
    }

    /**
     * Gets the value of the datiToponomastici property.
     * 
     * @return
     *     possible object is
     *     {@link DatiToponomastici }
     *     
     */
    public DatiToponomastici getDatiToponomastici() {
        return datiToponomastici;
    }

    /**
     * Sets the value of the datiToponomastici property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiToponomastici }
     *     
     */
    public void setDatiToponomastici(DatiToponomastici value) {
        this.datiToponomastici = value;
    }

    public boolean isSetDatiToponomastici() {
        return (this.datiToponomastici!= null);
    }

    /**
     * Gets the value of the datiCatastali property.
     * 
     * @return
     *     possible object is
     *     {@link DatiCatastali }
     *     
     */
    public DatiCatastali getDatiCatastali() {
        return datiCatastali;
    }

    /**
     * Sets the value of the datiCatastali property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiCatastali }
     *     
     */
    public void setDatiCatastali(DatiCatastali value) {
        this.datiCatastali = value;
    }

    public boolean isSetDatiCatastali() {
        return (this.datiCatastali!= null);
    }

    /**
     * Gets the value of the residenziale property.
     * 
     * @return
     *     possible object is
     *     {@link Residenziale }
     *     
     */
    public Residenziale getResidenziale() {
        return residenziale;
    }

    /**
     * Sets the value of the residenziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Residenziale }
     *     
     */
    public void setResidenziale(Residenziale value) {
        this.residenziale = value;
    }

    public boolean isSetResidenziale() {
        return (this.residenziale!= null);
    }

    /**
     * Gets the value of the nonResidenziale property.
     * 
     * @return
     *     possible object is
     *     {@link NonResidenziale }
     *     
     */
    public NonResidenziale getNonResidenziale() {
        return nonResidenziale;
    }

    /**
     * Sets the value of the nonResidenziale property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonResidenziale }
     *     
     */
    public void setNonResidenziale(NonResidenziale value) {
        this.nonResidenziale = value;
    }

    public boolean isSetNonResidenziale() {
        return (this.nonResidenziale!= null);
    }

}
