ACCEPT AM;
ACCEPT DIOGENE;

INSERT INTO AM_COMUNE SELECT codent, descrizione FROM &DIOGENE..SIT_ENTE;


INSERT INTO AM_COMUNE (BELFIORE, DESCRIZIONE) VALUES ( '9999', '-');
INSERT INTO AM_USER SELECT * FROM &AM..AM_USER;
INSERT INTO AM_ROLE SELECT * FROM &AM..AM_ROLE;
INSERT INTO AM_APPLICATION SELECT TIPO_APP AS NAME, TIPO_APP as APP_TYPE, CAT_APP as APP_CATEGORY FROM &AM..AM_APPLICATION;

INSERT INTO AM_INSTANCE SELECT NAME, TIPO_APP AS FK_AM_APPLICATION , URL  FROM &AM..AM_APPLICATION;

INSERT INTO AM_ITEM SELECT * FROM &AM..AM_ITEM;

INSERT INTO AM_APPLICATION_ITEM  SELECT AI.ID, A.tipo_app fk_am_application , AI.FK_AM_ITEM  FROM &AM..AM_APPLICATION_ITEM AI, &AM..AM_APPLICATION A WHERE AI.FK_AM_APPLICATION =A.NAME ;

INSERT INTO AM_PERMISSION SELECT * FROM &AM..AM_PERMISSION;

INSERT INTO AM_AI_ROLE SELECT ID, FK_AM_APPLICATION_ITEM, FK_AM_ROLE FROM &AM..AM_ITEM_ROLE;

INSERT INTO AM_USER_AIR SELECT FK_AM_ITEM_ROLE as FK_AM_AI_ROLE, FK_AM_USER FROM &AM..AM_USER_IR;

INSERT INTO AM_PERMISSION_AIR SELECT FK_AM_PERMISSION, FK_AM_ITEM_ROLE as FK_AM_AI_ROLE FROM &AM..AM_ROLE_PERMISSION;

commit;