CREATE TABLE AM_APPLICATION
(
  NAME          VARCHAR2(64 BYTE),
  APP_TYPE      VARCHAR2(1024 BYTE),
  APP_CATEGORY  VARCHAR2(1024 BYTE)
);


CREATE TABLE AM_COMUNE
(
  BELFIORE     VARCHAR2(64 BYTE),
  DESCRIZIONE  VARCHAR2(1024 BYTE)
);


CREATE TABLE AM_FONTE
(
  ID           INTEGER,
  CODICE       VARCHAR2(20 BYTE),
  DESCRIZIONE  VARCHAR2(255 BYTE),
  TIPO_FONTE   VARCHAR2(1 BYTE),
  N_ORDINE     INTEGER
);

COMMENT ON COLUMN AM_FONTE.ID IS 'IDENTIFICATIVO PER RETROCOMPATIBILITA CON SIT_ENTE_SORGENTE';

COMMENT ON COLUMN AM_FONTE.TIPO_FONTE IS 'I/E';


CREATE TABLE AM_FONTE_COMUNE
(
  FK_AM_COMUNE  VARCHAR2(64 BYTE),
  FK_AM_FONTE   INTEGER
);


CREATE TABLE AM_FONTE_TIPOINFO
(
  FK_AM_FONTE        INTEGER,
  INFORMAZIONE       VARCHAR2(2000 BYTE),
  PROG_OLD           INTEGER,
  N_ORDINE_SU_FONTE  INTEGER
);

COMMENT ON COLUMN AM_FONTE_TIPOINFO.N_ORDINE_SU_FONTE IS 'NUMERO ORDINE INTERNO ALLA STESSA fk_am_fonte';


CREATE TABLE AM_GROUP
(
  NAME          VARCHAR2(64 BYTE),
  FK_AM_COMUNE  VARCHAR2(64 BYTE)
);


CREATE TABLE AM_INSTANCE
(
  NAME               VARCHAR2(64 BYTE),
  FK_AM_APPLICATION  VARCHAR2(64 BYTE),
  URL                VARCHAR2(1024 BYTE)
);


CREATE TABLE AM_INSTANCE_COMUNE
(
  FK_AM_COMUNE    VARCHAR2(64 BYTE),
  FK_AM_INSTANCE  VARCHAR2(64 BYTE)
);


CREATE TABLE AM_ITEM
(
  NAME  VARCHAR2(64 BYTE)
);


CREATE TABLE AM_PERMISSION
(
  NAME        VARCHAR2(64 BYTE),
  FK_AM_ITEM  VARCHAR2(64 BYTE)
);


CREATE TABLE AM_ROLE
(
  NAME  VARCHAR2(64 BYTE)
);


CREATE TABLE AM_SECTION
(
  NAME               VARCHAR2(1024 BYTE),
  TIPO               INTEGER,
  FK_AM_APPLICATION  VARCHAR2(64 BYTE),
  FK_AM_FONTE        NUMBER,
  N_ORDINE           INTEGER,
  ID                 INTEGER
);

COMMENT ON COLUMN AM_SECTION.N_ORDINE IS 'N. ORDINE INTERNO AD APPLICATION O FONTE';


CREATE TABLE AM_USER
(
  NAME           VARCHAR2(64 BYTE),
  PWD            VARCHAR2(1024 BYTE),
  DT_INS         DATE,
  USER_INS       VARCHAR2(1024 BYTE),
  LAST_ACCESS    DATE,
  DISABLE_CAUSE  VARCHAR2(1024 BYTE),
  DT_UPD_PWD     DATE
);


CREATE TABLE AM_USER_GROUP
(
  FK_AM_GROUP  VARCHAR2(64 BYTE),
  FK_AM_USER   VARCHAR2(64 BYTE)
);


CREATE UNIQUE INDEX FK_AM_USER_GROUP ON AM_USER_GROUP
(FK_AM_USER, FK_AM_GROUP);


CREATE UNIQUE INDEX PK_AM_APPLICATION ON AM_APPLICATION
(NAME);


CREATE UNIQUE INDEX PK_AM_COMUNE ON AM_COMUNE
(BELFIORE);


CREATE UNIQUE INDEX PK_AM_FONTE ON AM_FONTE
(ID);


CREATE UNIQUE INDEX PK_AM_FONTE_COMUNE ON AM_FONTE_COMUNE
(FK_AM_FONTE, FK_AM_COMUNE);


CREATE UNIQUE INDEX PK_AM_FONTE_TIPOINFO ON AM_FONTE_TIPOINFO
(FK_AM_FONTE, INFORMAZIONE);


CREATE UNIQUE INDEX PK_AM_GROUP ON AM_GROUP
(NAME);


CREATE UNIQUE INDEX PK_AM_INSTANCE ON AM_INSTANCE
(NAME);


CREATE UNIQUE INDEX PK_AM_INSTANCE_COMUNE ON AM_INSTANCE_COMUNE
(FK_AM_COMUNE, FK_AM_INSTANCE);


CREATE UNIQUE INDEX PK_AM_ITEM ON AM_ITEM
(NAME);


CREATE UNIQUE INDEX PK_AM_PERMISSION ON AM_PERMISSION
(NAME);


CREATE UNIQUE INDEX PK_AM_ROLE ON AM_ROLE
(NAME);


CREATE UNIQUE INDEX PK_AM_SECTION ON AM_SECTION
(ID);


CREATE UNIQUE INDEX PK_AM_USER ON AM_USER
(NAME);


CREATE UNIQUE INDEX UK_AM_SECTION ON AM_SECTION
(NAME, FK_AM_APPLICATION);


CREATE TABLE AM_ANAGRAFICA
(
  ID                   INTEGER,
  CAP                  VARCHAR2(8 BYTE),
  CITTADINANZA         VARCHAR2(64 BYTE),
  CODICE_FISCALE       VARCHAR2(16 BYTE),
  COGNOME              VARCHAR2(64 BYTE),
  COMUNE_NASCITA       VARCHAR2(64 BYTE),
  COMUNE_RESIDENZA     VARCHAR2(64 BYTE),
  DATA_NASCITA         DATE,
  INDIRIZZO            VARCHAR2(64 BYTE),
  NOME                 VARCHAR2(64 BYTE),
  NUMERO               VARCHAR2(8 BYTE),
  PROVINCIA_NASCITA    VARCHAR2(64 BYTE),
  PROVINCIA_RESIDENZA  VARCHAR2(64 BYTE),
  SESSO                VARCHAR2(8 BYTE),
  FK_AM_USER           VARCHAR2(64 BYTE),
  FK_CET_ANAGRAGICA    INTEGER
);


CREATE TABLE AM_APPLICATION_ITEM
(
  ID                 INTEGER,
  FK_AM_APPLICATION  VARCHAR2(64 BYTE),
  FK_AM_ITEM         VARCHAR2(64 BYTE)
);


CREATE TABLE AM_KEY_VALUE
(
  KEY_CONF           VARCHAR2(64 BYTE),
  VALUE_CONF         VARCHAR2(2048 BYTE),
  KEY_INDEX          INTEGER,
  DELETED            DATE,
  MUST_BE_SET        VARCHAR2(1 BYTE),
  OVERW_TYPE         VARCHAR2(3 BYTE),
  SECTION_NAME       VARCHAR2(1024 BYTE),
  FK_AM_APPLICATION  VARCHAR2(64 BYTE),
  DESCRIZIONE_KEY    VARCHAR2(1024 BYTE),
  ID                 INTEGER
);

COMMENT ON COLUMN AM_KEY_VALUE.MUST_BE_SET IS 'Y=DEVE ESSERE INIZIALIZZATA, N=NO';

COMMENT ON COLUMN AM_KEY_VALUE.OVERW_TYPE IS '0 = non vincolato, 1= istanza, 2=comune , 3 istanza/comune, 4 fonte /comune, 99 non permesso';


CREATE TABLE AM_KEY_VALUE_EXT
(
  KEY_CONF           VARCHAR2(64 BYTE),
  VALUE_CONF         VARCHAR2(2048 BYTE),
  EXT_TYPE           VARCHAR2(1 BYTE),
  FK_AM_COMUNE       VARCHAR2(64 BYTE),
  FK_AM_INSTANCE     VARCHAR2(64 BYTE),
  FK_AM_FONTE        INTEGER,
  SECTION_NAME       VARCHAR2(1024 BYTE),
  FK_AM_APPLICATION  VARCHAR2(64 BYTE),
  ID                 INTEGER
);

COMMENT ON COLUMN AM_KEY_VALUE_EXT.EXT_TYPE IS '0 add, 1 replace, 2 remove, 3 set';


CREATE UNIQUE INDEX FK_AM_APPLICATION_ITEM ON AM_APPLICATION_ITEM
(FK_AM_APPLICATION, FK_AM_ITEM);


CREATE INDEX IDX_KEY_VALUE_EXT ON AM_KEY_VALUE_EXT
(KEY_CONF, SECTION_NAME, FK_AM_APPLICATION);


CREATE UNIQUE INDEX PK_AM_ANAGRAFICA ON AM_ANAGRAFICA
(ID);


CREATE UNIQUE INDEX PK_AM_APPLICATION_ITEM ON AM_APPLICATION_ITEM
(ID);


CREATE UNIQUE INDEX PK_AM_KEY_VALUE ON AM_KEY_VALUE
(ID);


CREATE UNIQUE INDEX PK_AM_KEY_VALUE_EXT ON AM_KEY_VALUE_EXT
(ID);


CREATE UNIQUE INDEX UK_AM_KEY_VALUE ON AM_KEY_VALUE
(KEY_CONF, SECTION_NAME, FK_AM_APPLICATION);


CREATE TABLE AM_AI_ROLE
(
  ID                      INTEGER,
  FK_AM_APPLICATION_ITEM  INTEGER,
  FK_AM_ROLE              VARCHAR2(64 BYTE)
);


CREATE TABLE AM_GROUP_AIR
(
  FK_AM_AI_ROLE  INTEGER,
  FK_AM_GROUP    VARCHAR2(64 BYTE)
);


CREATE TABLE AM_PERMISSION_AIR
(
  FK_AM_PERMISSION  VARCHAR2(64 BYTE),
  FK_AM_AI_ROLE     INTEGER
);


CREATE TABLE AM_USER_AIR
(
  FK_AM_AI_ROLE  INTEGER,
  FK_AM_USER     VARCHAR2(64 BYTE)
);


CREATE UNIQUE INDEX FK_AM_AI_ROLE ON AM_AI_ROLE
(FK_AM_ROLE, FK_AM_APPLICATION_ITEM);


CREATE UNIQUE INDEX FK_AM_GROUP_AIR ON AM_GROUP_AIR
(FK_AM_GROUP, FK_AM_AI_ROLE);


CREATE UNIQUE INDEX FK_AM_PERMISSION_AIR ON AM_PERMISSION_AIR
(FK_AM_PERMISSION, FK_AM_AI_ROLE);


CREATE UNIQUE INDEX FK_AM_USER_AIR ON AM_USER_AIR
(FK_AM_USER, FK_AM_AI_ROLE);


CREATE UNIQUE INDEX PK_AM_AI_ROLE ON AM_AI_ROLE
(ID);


ALTER TABLE AM_APPLICATION ADD (
  CONSTRAINT PK_AM_APPLICATION
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_COMUNE ADD (
  CONSTRAINT PK_AM_COMUNE
 PRIMARY KEY
 (BELFIORE));

ALTER TABLE AM_FONTE ADD (
  CONSTRAINT PK_AM_FONTE
 PRIMARY KEY
 (ID));

ALTER TABLE AM_FONTE_COMUNE ADD (
  CONSTRAINT PK_AM_FONTE_COMUNE
 PRIMARY KEY
 (FK_AM_FONTE, FK_AM_COMUNE));

ALTER TABLE AM_FONTE_TIPOINFO ADD (
  CONSTRAINT PK_AM_FONTE_TIPOINFO
 PRIMARY KEY
 (FK_AM_FONTE, INFORMAZIONE));

ALTER TABLE AM_GROUP ADD (
  CONSTRAINT PK_AM_GROUP
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_INSTANCE ADD (
  CONSTRAINT PK_AM_INSTANCE
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_INSTANCE_COMUNE ADD (
  CONSTRAINT PK_AM_INSTANCE_COMUNE
 PRIMARY KEY
 (FK_AM_COMUNE, FK_AM_INSTANCE));

ALTER TABLE AM_ITEM ADD (
  CONSTRAINT PK_AM_ITEM
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_PERMISSION ADD (
  CONSTRAINT PK_AM_PERMISSION
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_ROLE ADD (
  CONSTRAINT PK_AM_ROLE
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_SECTION ADD (
  CONSTRAINT PK_AM_SECTION
 PRIMARY KEY
 (ID),
  CONSTRAINT UK_AM_SECTION
 UNIQUE (NAME, FK_AM_APPLICATION));

ALTER TABLE AM_USER ADD (
  CONSTRAINT PK_AM_USER
 PRIMARY KEY
 (NAME));

ALTER TABLE AM_ANAGRAFICA ADD (
  CONSTRAINT PK_AM_ANAGRAFICA
 PRIMARY KEY
 (ID));

ALTER TABLE AM_APPLICATION_ITEM ADD (
  CONSTRAINT PK_AM_APPLICATION_ITEM
 PRIMARY KEY
 (ID));

ALTER TABLE AM_KEY_VALUE ADD (
  CONSTRAINT PK_AM_KEY_VALUE
 PRIMARY KEY
 (ID),
  CONSTRAINT UK_AM_KEY_VALUE
 UNIQUE (KEY_CONF, SECTION_NAME, FK_AM_APPLICATION));

ALTER TABLE AM_KEY_VALUE_EXT ADD (
  CONSTRAINT PK_AM_KEY_VALUE_EXT
 PRIMARY KEY
 (ID));

ALTER TABLE AM_AI_ROLE ADD (
  CONSTRAINT PK_AM_AI_ROLE
 PRIMARY KEY
 (ID));

ALTER TABLE AM_FONTE_COMUNE ADD (
  CONSTRAINT FK_AM_FONTE_COMUNE_COMUNE 
 FOREIGN KEY (FK_AM_COMUNE) 
 REFERENCES AM_COMUNE (BELFIORE),
  CONSTRAINT FK_AM_FONTE_COMUNE_FONTE 
 FOREIGN KEY (FK_AM_FONTE) 
 REFERENCES AM_FONTE (ID));

ALTER TABLE AM_FONTE_TIPOINFO ADD (
  CONSTRAINT FK_FONTE_TIPOINFO_FONTE 
 FOREIGN KEY (FK_AM_FONTE) 
 REFERENCES AM_FONTE (ID));

ALTER TABLE AM_GROUP ADD (
  CONSTRAINT FK_AM_GROUP_AM_COMUNE 
 FOREIGN KEY (FK_AM_COMUNE) 
 REFERENCES AM_COMUNE (BELFIORE));

ALTER TABLE AM_INSTANCE_COMUNE ADD (
  CONSTRAINT FK_AM_IC_AM_COMUNE 
 FOREIGN KEY (FK_AM_COMUNE) 
 REFERENCES AM_COMUNE (BELFIORE),
  CONSTRAINT FK_AM_IC_AM_INSTANCE 
 FOREIGN KEY (FK_AM_INSTANCE) 
 REFERENCES AM_INSTANCE (NAME));

ALTER TABLE AM_PERMISSION ADD (
  CONSTRAINT FK_AM_PERMISSION_AM_ITEM 
 FOREIGN KEY (FK_AM_ITEM) 
 REFERENCES AM_ITEM (NAME));

ALTER TABLE AM_SECTION ADD (
  CONSTRAINT FK_AM_SECTION_AM_APPLICATION 
 FOREIGN KEY (FK_AM_APPLICATION) 
 REFERENCES AM_APPLICATION (NAME),
  CONSTRAINT FK_AM_SECTION_FONTE 
 FOREIGN KEY (FK_AM_FONTE) 
 REFERENCES AM_FONTE (ID));

ALTER TABLE AM_USER_GROUP ADD (
  CONSTRAINT FK_AM_USER_GROUP_AM_GROUP 
 FOREIGN KEY (FK_AM_GROUP) 
 REFERENCES AM_GROUP (NAME),
  CONSTRAINT FK_AM_USER_GROUP_AM_USER 
 FOREIGN KEY (FK_AM_USER) 
 REFERENCES AM_USER (NAME));

ALTER TABLE AM_ANAGRAFICA ADD (
  CONSTRAINT FK_AM_ANAGRAFICA_AM_USER 
 FOREIGN KEY (FK_AM_USER) 
 REFERENCES AM_USER (NAME));

ALTER TABLE AM_APPLICATION_ITEM ADD (
  CONSTRAINT FK_AM_AI_AM_APPLICATION 
 FOREIGN KEY (FK_AM_APPLICATION) 
 REFERENCES AM_APPLICATION (NAME),
  CONSTRAINT FK_AM_AI_AM_ITEM 
 FOREIGN KEY (FK_AM_ITEM) 
 REFERENCES AM_ITEM (NAME));

ALTER TABLE AM_KEY_VALUE ADD (
  CONSTRAINT FK_KEY_VALUE_SECTION 
 FOREIGN KEY (SECTION_NAME, FK_AM_APPLICATION) 
 REFERENCES AM_SECTION (NAME,FK_AM_APPLICATION));

ALTER TABLE AM_KEY_VALUE_EXT ADD (
  CONSTRAINT FK_AM_KEY_VALUE_EXT_AM_COMUNE 
 FOREIGN KEY (FK_AM_COMUNE) 
 REFERENCES AM_COMUNE (BELFIORE),
  CONSTRAINT FK_AM_KEY_VALUE_EXT_AM_INST 
 FOREIGN KEY (FK_AM_INSTANCE) 
 REFERENCES AM_INSTANCE (NAME),
  CONSTRAINT FK_AM_KEY_VALUE_EXT_INST_COM 
 FOREIGN KEY (FK_AM_COMUNE, FK_AM_INSTANCE) 
 REFERENCES AM_INSTANCE_COMUNE (FK_AM_COMUNE,FK_AM_INSTANCE),
  CONSTRAINT FK_KEY_EXT_FONTE_COMUNE 
 FOREIGN KEY (FK_AM_FONTE, FK_AM_COMUNE) 
 REFERENCES AM_FONTE_COMUNE (FK_AM_FONTE,FK_AM_COMUNE),
  CONSTRAINT FK_KEY_VALUE_EXT_SECTION 
 FOREIGN KEY (SECTION_NAME, FK_AM_APPLICATION) 
 REFERENCES AM_SECTION (NAME,FK_AM_APPLICATION));

ALTER TABLE AM_AI_ROLE ADD (
  CONSTRAINT FK_AM_AIR_AM_APPLICATION_ITEM 
 FOREIGN KEY (FK_AM_APPLICATION_ITEM) 
 REFERENCES AM_APPLICATION_ITEM (ID),
  CONSTRAINT FK_AM_AIR_AM_ROLE 
 FOREIGN KEY (FK_AM_ROLE) 
 REFERENCES AM_ROLE (NAME));

ALTER TABLE AM_GROUP_AIR ADD (
  CONSTRAINT FK_AM_GAIR_AM_AI_ROLE 
 FOREIGN KEY (FK_AM_AI_ROLE) 
 REFERENCES AM_AI_ROLE (ID),
  CONSTRAINT FK_AM_GAIR_AM_GROUP 
 FOREIGN KEY (FK_AM_GROUP) 
 REFERENCES AM_GROUP (NAME));

ALTER TABLE AM_PERMISSION_AIR ADD (
  CONSTRAINT FK_AM_PAIR_AM_GAI_ROLE 
 FOREIGN KEY (FK_AM_AI_ROLE) 
 REFERENCES AM_AI_ROLE (ID),
  CONSTRAINT FK_AM_PAIR_AM_PERMISSION 
 FOREIGN KEY (FK_AM_PERMISSION) 
 REFERENCES AM_PERMISSION (NAME));

ALTER TABLE AM_USER_AIR ADD (
  CONSTRAINT FK_AM_USER_AIR_AM_AI_ROLE 
 FOREIGN KEY (FK_AM_AI_ROLE) 
 REFERENCES AM_AI_ROLE (ID),
  CONSTRAINT FK_AM_USER_AIR_AM_USER 
 FOREIGN KEY (FK_AM_USER) 
 REFERENCES AM_USER (NAME));

