SELECT c.CODFISC AS CODICE_FISCALE
  FROM SIT_D_PERSONA c
 WHERE c.ID_EXT 
    IN 
   ( SELECT u.ID_EXT_D_PERSONA2
       FROM SIT_D_PERSONA p, SIT_D_UNIONE u
      WHERE p.id_ext = u.id_ext
        AND p.CODFISC = ? 
		AND U.DT_FINE_VAL IS NULL)
 	AND (DATA_MOR IS NULL OR DATA_MOR > ?)
