SELECT PC.POSIZ_ANA AS POSIANA,
 PC.DATA_IMM_PERSONA AS IMMDATA,
 PC.DATA_EMI_PERSONA AS EMIDATA,
 PC.DATA_MOR_PERSONA AS MORDATA,
 PC.ID_ORIG_VIA AS COD_VIA,
 TO_NUMBER(PC.CIV_LIV1) NUMERO_CIV
   FROM SIT_D_PERS_FAM PF, PERSONA_CIVICI_V PC
WHERE PF.ID_EXT_D_PERSONA = PC.ID_EXT_PERSONA
AND PF.DT_FINE_VAL IS NULL
AND PC.DT_FINE_VAL_PERSONA IS NULL
AND PC.CODFISC = ?
