package it.webred.AMProfiler.beans;


// Generated by Nicola Campanelli 24 august 2010

/**
 * AmApplication generated by hbm2java
 */
public class AmGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String name;
	private String fkAmComune;
	private String permRangeIp;
	private String permOraDa;
	private String permOraA;

	//mi serve quando voglio sapere se ad un utente è stato assegnato l' ItemRole  
	private boolean checked = false;
	//descrizione comune assegnato
	private String descrComune;
	
	// Constructors

	/** default constructor */
	public AmGroup() {
	}

	public boolean 	getChecked()
	{
		return checked;
	}

	public void setChecked(boolean checked)
	{
		this.checked = checked;
	}
	
	public String getDescrComune() {
		return descrComune;
	}

	public void setDescrComune(String descrComune) {
		this.descrComune = descrComune;
	}

	// Property accessors
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFkAmComune() {
		return fkAmComune;
	}

	public void setFkAmComune(String fkAmComune) {
		this.fkAmComune = fkAmComune;
	}

	public String getPermRangeIp() {
		return permRangeIp;
	}

	public void setPermRangeIp(String permRangeIp) {
		this.permRangeIp = permRangeIp;
	}

	public String getPermOraDa() {
		return permOraDa;
	}

	public void setPermOraDa(String permOraDa) {
		this.permOraDa = permOraDa;
	}

	public String getPermOraA() {
		return permOraA;
	}

	public void setPermOraA(String permOraA) {
		this.permOraA = permOraA;
	}
}
