package it.webred.AMProfiler.beans;

// Generated 7-lug-2006 12.31.07 by Hibernate Tools 3.1.0.beta5

import java.util.HashSet;
import java.util.Set;

/**
 * AmItem generated by hbm2java
 */
public class AmItem implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private AmApplication amApplication;
	private Set<AmPermission> amPermissions = new HashSet<AmPermission>(0);
	private Set<AmItemRole> amItemRoles = new HashSet<AmItemRole>(0);

	// Constructors

	/** default constructor */
	public AmItem() {
	}

	/** minimal constructor */
	public AmItem(String name) {
		this.name = name;
	}

	/** full constructor */
	public AmItem(String name, AmApplication amApplication, Set<AmPermission> amPermissions, Set<AmItemRole> amItemRoles) {
		this.name = name;
		this.amApplication = amApplication;
		this.amPermissions = amPermissions;
		this.amItemRoles = amItemRoles;
	}

	// Property accessors
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public AmApplication getAmApplication() {
		return amApplication;
	}

	public void setAmApplication(AmApplication amApplication) {
		this.amApplication = amApplication;
	}

	public Set<AmPermission> getAmPermissions() {
		return amPermissions;
	}

	public void setAmPermissions(Set<AmPermission> amPermissions) {
		this.amPermissions = amPermissions;
	}

	public Set<AmItemRole> getAmItemRoles() {
		return amItemRoles;
	}

	public void setAmItemRoles(Set<AmItemRole> amItemRoles) {
		this.amItemRoles = amItemRoles;
	}

}
