package it.webred.AMProfiler.beans;

// Generated 7-lug-2006 12.31.07 by Hibernate Tools 3.1.0.beta5


/**
 * AmItemRole generated by hbm2java
 */
public class AmItemRole implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long id;
	private String amAppItemS;
	private String amRoleS;

	// mi serve quando voglio sapere se ad un utente è stato assegnato l' ItemRole
	private boolean checked = false;

	// used to know if the item role is assigned by AM_GROUP_AIR
	// if the item role is linked to the user by AM_GROUP_AIR it must be checked
	// and must remain checked
	private boolean grouped = false;

	// Constructors

	/** default constructor */
	public AmItemRole() {
	}

	/** minimal constructor */
	public AmItemRole(long id) {
		this.id = id;
	}

	/**
	 * full constructor public AmItemRole(long id, AmItem amItem, AmRole
	 * amRole,String amItemS, String amRoleS, Set<AmUserIr> amUserIrs,
	 * Set<AmRolePermission> amRolePermissions) { this.id = id; this.amItem =
	 * amItem; this.amRole = amRole; this.amItemS = amItemS; this.amRoleS =
	 * amRoleS; this.amUserIrs = amUserIrs; this.amRolePermissions =
	 * amRolePermissions; }
	 */

	// Property accessors
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getAmAppItemS() {
		return amAppItemS;
	}

	public void setAmAppItemS(String amItemS) {
		amAppItemS = amItemS;
	}

	public String getAmRoleS() {
		return amRoleS;
	}

	public void setAmRoleS(String amRoleS) {
		this.amRoleS = amRoleS;
	}

	public boolean getChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	public void setGrouped(boolean grouped) {
		this.grouped = grouped;
	}

	public boolean isGrouped() {
		return grouped;
	}

}
