package it.webred.AMProfiler.beans;

// Generated 7-lug-2006 12.31.07 by Hibernate Tools 3.1.0.beta5

/**
 * AmRolePermission generated by hbm2java
 */
public class AmRolePermission implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AmRolePermissionId id;
	private AmItemRole amItemRole;
	private AmPermission amPermission;

	// Constructors

	/** default constructor */
	public AmRolePermission() {
	}

	/** full constructor */
	public AmRolePermission(AmRolePermissionId id, AmItemRole amItemRole, AmPermission amPermission) {
		this.id = id;
		this.amItemRole = amItemRole;
		this.amPermission = amPermission;
	}

	// Property accessors
	public AmRolePermissionId getId() {
		return id;
	}

	public void setId(AmRolePermissionId id) {
		this.id = id;
	}

	public AmItemRole getAmItemRole() {
		return amItemRole;
	}

	public void setAmItemRole(AmItemRole amItemRole) {
		this.amItemRole = amItemRole;
	}

	public AmPermission getAmPermission() {
		return amPermission;
	}

	public void setAmPermission(AmPermission amPermission) {
		this.amPermission = amPermission;
	}

}
