package it.webred.AMProfiler.beans;

// Generated 7-lug-2006 12.31.07 by Hibernate Tools 3.1.0.beta5


/**
 * AmUser generated by hbm2java
 */
public class AmUser implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private String pwd;
	private String dt_upd_pwd = "";
	private String DISABLE_CAUSE = "";

	private boolean checked = false;
	// private Set<AmUserIr> amUserIrs = new HashSet<AmUserIr>(0);
	// private Set<AmGroup> amGroups = new HashSet<AmGroup>(0);

	// Constructors

	/** default constructor */
	public AmUser() {
	}

	/** minimal constructor */
	public AmUser(String name) {
		this.name = name;
	}

	// /** full constructor */
	// public AmUser(String name, String pwd, Set<AmUserIr> amUserIrs)
	// {
	// this.name = name;
	// this.pwd = pwd;
	// this.amUserIrs = amUserIrs;
	// }

	/** full constructor */
	public AmUser(String name, String pwd) {
		this.name = name;
		this.pwd = pwd;
	}

	// Property accessors
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getDt_upd_pwd() {
		return dt_upd_pwd;
	}

	public void setDt_upd_pwd(String dtUpdPwd) {
		dt_upd_pwd = dtUpdPwd;
	}

	public String getDISABLE_CAUSE() {
		return DISABLE_CAUSE;
	}

	public void setDISABLE_CAUSE(String dISABLECAUSE) {
		DISABLE_CAUSE = dISABLECAUSE;
	}

	public boolean isChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	// public Set<AmUserIr> getAmUserIrs()
	// {
	// return this.amUserIrs;
	// }
	//
	// public void setAmUserIrs(Set<AmUserIr> amUserIrs)
	// {
	// this.amUserIrs = amUserIrs;
	// }
	//
	// public Set<AmGroup> getAmGroups()
	// {
	// return this.amGroups;
	// }
	//
	// public void setAmGroups(Set<AmGroup> amGroups)
	// {
	// this.amGroups = amGroups;
	// }

}
