CREATE OR REPLACE VIEW VW_ANAGRAFE
(TIPO_SOGGETTO, CODICE_FISCALE, COGNOME, NOME, SESSO, 
 DATA_NASCITA, DESCR_COMUNE_NASCITA, DESCR_INDIRIZZO)
AS 
(
Select ANA.POSIZ_ANA TIPO_SOGGETTO,
       ANA.CODFISC CODICE_FISCALE,
       ANA.COGNOME,
       ANA.NOME,
       ANA.SESSO,
       ANA.DATA_NASCITA,
       c.DESCRIZIONE DESCR_COMUNE_NASCITA,
       ltrim(ANA.VIASEDIME || ' ' || ANA.DESCRIZIONE_VIA || ' ' || ltrim(ANA.CIV_LIV1,'0') || '/' || ANA.CIV_LIV2 ) AS DESCR_INDIRIZZO
       from 
       diogene.sit_comune c,
       diogene.persona_civici_v ANA
       where 
       ANA.ID_EXT_COMUNE_NASCITA = c.ID_EXT        
       and c.DT_FINE_VAL is null         
       and ana.dt_fine_val_persona is null
)
/


CREATE OR REPLACE VIEW VW_CONTRIBUENTI
(PK_SEQU_CONTRIBUENTI, UK_CODI_CONTRIBUENTE, CODENTE, CODICE_CONTRIBUENTE, CODICE_FISCALE, 
 PARTITA_IVA, DENOMINAZIONE, COGNOME, NOME, SESSO, 
 DATA_NASCITA, DESCR_COMUNE_NASCITA, DESCR_INDIRIZZO, INTERNO, COMUNE_RESIDENZA, 
 FK_CIVICI, FK_ANAGRAFE, FK_COMUNI, DATA_VALIDITA, PROVENIENZA)
AS 
(
SELECT "PK_SEQU_CONTRIBUENTI","UK_CODI_CONTRIBUENTE","CODENTE","CODICE_CONTRIBUENTE","CODICE_FISCALE","PARTITA_IVA","DENOMINAZIONE","COGNOME","NOME","SESSO","DATA_NASCITA","DESCR_COMUNE_NASCITA","DESCR_INDIRIZZO","INTERNO","COMUNE_RESIDENZA","FK_CIVICI","FK_ANAGRAFE","FK_COMUNI","DATA_VALIDITA","PROVENIENZA" FROM DBTOTALE.TRI_CONTRIBUENTI
         WHERE PROVENIENZA = 'T'
)
/


CREATE OR REPLACE VIEW VW_OGGETTI_ICI
(IMMD, FOGLIO_CATASTO, PARTICELLA_CATASTO, SUBALTERNO_CATASTO, CATEGORIA_CATASTALE, 
 CLASSE, RENDITA_CATASTALE, VALORE_CATASTALE, TITOLO_POSSESSO, QUOTA_POSSESSO, 
 DEN_RIFERIMENTO, DIC_POSSEDUTO, TIP_DEN, DATA_INIZIO_POSSESSO, DATA_FINE_POSSESSO, 
 ABITAZIONE_PRINCIPALE, FK_CONTRIBUENTE, PROVENIENZA)
AS 
(
SELECT IMMD, 
  FOGLIO_CATASTO, 
  PARTICELLA_CATASTO, 
  SUBALTERNO_CATASTO, 
  CATEGORIA_CATASTALE, 
  CLASSE, 
  RENDITA_CATASTALE, 
  VALORE_CATASTALE, 
  TITOLO_POSSESSO, 
  QUOTA_POSSESSO, 
  DEN_RIFERIMENTO, 
  DIC_POSSEDUTO, 
  TIP_DEN, 
  DATA_INIZIO_POSSESSO, 
  DATA_FINE_POSSESSO, 
  ABITAZIONE_PRINCIPALE,
  FK_CONTRIBUENTE, 
  PROVENIENZA
  FROM DBTOTALE.TRI_OGGETTI_ICI
         WHERE PROVENIENZA = 'T'
)
/


CREATE OR REPLACE VIEW VW_SITICONDUZ_IMM_ALL
(COD_NAZIONALE, FOGLIO, PARTICELLA, SUB, UNIMM, 
 TIPO_TITOLO, PERC_POSS, TIPO_DOCUMENTO, TIT_NO_COD, VALIDO_INIZIO, 
 VALIDO_FINE, ATTO_INIZIO, ATTO_FINE, PK_CUAA, CUAA, 
 DATA_INIZIO, DATA_FINE)
AS 
(
SELECT "COD_NAZIONALE","FOGLIO","PARTICELLA","SUB","UNIMM","TIPO_TITOLO","PERC_POSS","TIPO_DOCUMENTO","TIT_NO_COD","VALIDO_INIZIO","VALIDO_FINE","ATTO_INIZIO","ATTO_FINE","PK_CUAA","CUAA","DATA_INIZIO","DATA_FINE" FROM SITI.SITICONDUZ_IMM_ALL
)
/


