package it.webred.AMProfiler.beans;

// Generated by Nicola Campanelli 24 august 2010

/**
 * AmApplication generated by hbm2java
 */
public class AmGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String name;

	//mi serve quando voglio sapere se ad un utente è stato assegnato l' ItemRole  
	private boolean checked = false;
	
	// Constructors

	/** default constructor */
	public AmGroup() {
	}

	public boolean 	getChecked()
	{
		return checked;
	}

	public void setChecked(boolean checked)
	{
		this.checked = checked;
	}
	
	// Property accessors
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
