package it.webred.AMProfiler.beans;

// Generated 7-lug-2006 12.31.07 by Hibernate Tools 3.1.0.beta5


/**
 * AmItemRole generated by hbm2java
 */
public class AmUserGroup implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String amUserS;
	private String amGroupS;

	// Constructors

	/** default constructor */
	public AmUserGroup() {
	}

	/** minimal constructor */
	public AmUserGroup(long id) {
		this.id = id;
	}

	public String getAmUserS() {
		return amUserS;
	}

	public void setAmUserS(String amUserS) {
		this.amUserS = amUserS;
	}

	public String getAmGroupS() {
		return amGroupS;
	}

	public void setAmGroupS(String amGroupS) {
		this.amGroupS = amGroupS;
	}

	// Property accessors
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
