package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4



/**
 * DcAttribute generated by hbm2java
 */

public class DcAttribute  implements java.io.Serializable {


    // Fields    

     private Long id;
     private DcColumn dcColumn;
     private String attributeSpec;
     private String attributeVal;


    // Constructors

    /** default constructor */
    public DcAttribute() {
    }

	/** minimal constructor */
    public DcAttribute(Long id, String attributeSpec) {
        this.id = id;
        this.attributeSpec = attributeSpec;
    }
    
    /** full constructor */
    public DcAttribute(Long id, DcColumn dcColumn, String attributeSpec, String attributeVal) {
        this.id = id;
        this.dcColumn = dcColumn;
        this.attributeSpec = attributeSpec;
        this.attributeVal = attributeVal;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public DcColumn getDcColumn() {
        return this.dcColumn;
    }
    
    public void setDcColumn(DcColumn dcColumn) {
        this.dcColumn = dcColumn;
    }

    public String getAttributeSpec() {
        return this.attributeSpec;
    }
    
    public void setAttributeSpec(String attributeSpec) {
        this.attributeSpec = attributeSpec;
    }

    public String getAttributeVal() {
        return this.attributeVal;
    }
    
    public void setAttributeVal(String attributeVal) {
        this.attributeVal = attributeVal;
    }
   








}
