package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * DcColumn generated by hbm2java
 */

public class DcColumn  implements java.io.Serializable {


    // Fields    

     private Long id;
     private DcEntity dcEntity;
     private DcExpression dcExpression;
     private String longDesc;
     private Set dvUeGroups = new HashSet(0);
     private Set dcTipoeColumns = new HashSet(0);
     private Set dcAttributes = new HashSet(0);


    // Constructors

    /** default constructor */
    public DcColumn() {
    }

	/** minimal constructor */
    public DcColumn(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public DcColumn(Long id, DcEntity dcEntity, DcExpression dcExpression, String longDesc, Set dvUeGroups, Set dcTipoeColumns, Set dcAttributes) {
        this.id = id;
        this.dcEntity = dcEntity;
        this.dcExpression = dcExpression;
        this.longDesc = longDesc;
        this.dvUeGroups = dvUeGroups;
        this.dcTipoeColumns = dcTipoeColumns;
        this.dcAttributes = dcAttributes;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public DcEntity getDcEntity() {
        return this.dcEntity;
    }
    
    public void setDcEntity(DcEntity dcEntity) {
        this.dcEntity = dcEntity;
    }

    public DcExpression getDcExpression() {
        return this.dcExpression;
    }
    
    public void setDcExpression(DcExpression dcExpression) {
        this.dcExpression = dcExpression;
    }

    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }

    public Set getDvUeGroups() {
        return this.dvUeGroups;
    }
    
    public void setDvUeGroups(Set dvUeGroups) {
        this.dvUeGroups = dvUeGroups;
    }

    public Set getDcTipoeColumns() {
        return this.dcTipoeColumns;
    }
    
    public void setDcTipoeColumns(Set dcTipoeColumns) {
        this.dcTipoeColumns = dcTipoeColumns;
    }

    public Set getDcAttributes() {
        return this.dcAttributes;
    }
    
    public void setDcAttributes(Set dcAttributes) {
        this.dcAttributes = dcAttributes;
    }
   








}
