package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * DcEntity generated by hbm2java
 */

public class DcEntity  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String longDesc;
     private String name;
     private String owner;
     private String userIns;
     private Date dtIns;
     private String userMod;
     private Date dtMod;
     private Set dcEntityRelsForFkDcEntity1 = new HashSet(0);
     private Set dvUeFromEntities = new HashSet(0);
     private Set dvKeies = new HashSet(0);
     private Set dcEntityRelsForFkDcEntity2 = new HashSet(0);
     private Set dcSchemaEntities = new HashSet(0);
     private Set dvUserEntities = new HashSet(0);
     private Set dcColumns = new HashSet(0);


    // Constructors

    /** default constructor */
    public DcEntity() {
    }

	/** minimal constructor */
    public DcEntity(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public DcEntity(Long id, String longDesc, String name, String owner, String userIns, Date dtIns, String userMod, Date dtMod, Set dcEntityRelsForFkDcEntity1, Set dvUeFromEntities, Set dvKeies, Set dcEntityRelsForFkDcEntity2, Set dcSchemaEntities, Set dvUserEntities, Set dcColumns) {
        this.id = id;
        this.longDesc = longDesc;
        this.name = name;
        this.owner = owner;
        this.userIns = userIns;
        this.dtIns = dtIns;
        this.userMod = userMod;
        this.dtMod = dtMod;
        this.dcEntityRelsForFkDcEntity1 = dcEntityRelsForFkDcEntity1;
        this.dvUeFromEntities = dvUeFromEntities;
        this.dvKeies = dvKeies;
        this.dcEntityRelsForFkDcEntity2 = dcEntityRelsForFkDcEntity2;
        this.dcSchemaEntities = dcSchemaEntities;
        this.dvUserEntities = dvUserEntities;
        this.dcColumns = dcColumns;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getLongDesc() {
        return this.longDesc;
    }
    
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getUserIns() {
        return this.userIns;
    }
    
    public void setUserIns(String userIns) {
        this.userIns = userIns;
    }

    public Date getDtIns() {
        return this.dtIns;
    }
    
    public void setDtIns(Date dtIns) {
        this.dtIns = dtIns;
    }

    public String getUserMod() {
        return this.userMod;
    }
    
    public void setUserMod(String userMod) {
        this.userMod = userMod;
    }

    public Date getDtMod() {
        return this.dtMod;
    }
    
    public void setDtMod(Date dtMod) {
        this.dtMod = dtMod;
    }

    public Set getDcEntityRelsForFkDcEntity1() {
        return this.dcEntityRelsForFkDcEntity1;
    }
    
    public void setDcEntityRelsForFkDcEntity1(Set dcEntityRelsForFkDcEntity1) {
        this.dcEntityRelsForFkDcEntity1 = dcEntityRelsForFkDcEntity1;
    }

    public Set getDvUeFromEntities() {
        return this.dvUeFromEntities;
    }
    
    public void setDvUeFromEntities(Set dvUeFromEntities) {
        this.dvUeFromEntities = dvUeFromEntities;
    }

    public Set getDvKeies() {
        return this.dvKeies;
    }
    
    public void setDvKeies(Set dvKeies) {
        this.dvKeies = dvKeies;
    }

    public Set getDcEntityRelsForFkDcEntity2() {
        return this.dcEntityRelsForFkDcEntity2;
    }
    
    public void setDcEntityRelsForFkDcEntity2(Set dcEntityRelsForFkDcEntity2) {
        this.dcEntityRelsForFkDcEntity2 = dcEntityRelsForFkDcEntity2;
    }

    public Set getDcSchemaEntities() {
        return this.dcSchemaEntities;
    }
    
    public void setDcSchemaEntities(Set dcSchemaEntities) {
        this.dcSchemaEntities = dcSchemaEntities;
    }

    public Set getDvUserEntities() {
        return this.dvUserEntities;
    }
    
    public void setDvUserEntities(Set dvUserEntities) {
        this.dvUserEntities = dvUserEntities;
    }

    public Set getDcColumns() {
        return this.dcColumns;
    }
    
    public void setDcColumns(Set dcColumns) {
        this.dcColumns = dcColumns;
    }
   








}
