package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * DcExpression generated by hbm2java
 */

public class DcExpression  implements java.io.Serializable {


    // Fields    

     private Long id;
     private byte[] expression;
     private String alias;
     private String colType;
     private Set dvUeOrders = new HashSet(0);
     private Set dcColumns = new HashSet(0);


    // Constructors

    /** default constructor */
    public DcExpression() {
    }

	/** minimal constructor */
    public DcExpression(Long id, byte[] expression) {
        this.id = id;
        this.expression = expression;
    }
    
    /** full constructor */
    public DcExpression(Long id, byte[] expression, String alias, String colType, Set dvUeOrders, Set dcColumns) {
        this.id = id;
        this.expression = expression;
        this.alias = alias;
        this.colType = colType;
        this.dvUeOrders = dvUeOrders;
        this.dcColumns = dcColumns;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getExpression() {
        return this.expression;
    }
    
    public void setExpression(byte[] expression) {
        this.expression = expression;
    }

    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getColType() {
        return this.colType;
    }
    
    public void setColType(String colType) {
        this.colType = colType;
    }

    public Set getDvUeOrders() {
        return this.dvUeOrders;
    }
    
    public void setDvUeOrders(Set dvUeOrders) {
        this.dvUeOrders = dvUeOrders;
    }

    public Set getDcColumns() {
        return this.dcColumns;
    }
    
    public void setDcColumns(Set dcColumns) {
        this.dcColumns = dcColumns;
    }
   








}
