package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4



/**
 * DcMetadataConnection generated by hbm2java
 */

public class DcMetadataConnection  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String name;
     private String driverClass;
     private String connString;
     private String userName;
     private String password;
     private String dbtype;
     private byte[] hibernateMapping;


    // Constructors

    /** default constructor */
    public DcMetadataConnection() {
    }

	/** minimal constructor */
    public DcMetadataConnection(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public DcMetadataConnection(Long id, String name, String driverClass, String connString, String userName, String password, String dbtype, byte[] hibernateMapping) {
        this.id = id;
        this.name = name;
        this.driverClass = driverClass;
        this.connString = connString;
        this.userName = userName;
        this.password = password;
        this.dbtype = dbtype;
        this.hibernateMapping = hibernateMapping;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDriverClass() {
        return this.driverClass;
    }
    
    public void setDriverClass(String driverClass) {
        this.driverClass = driverClass;
    }

    public String getConnString() {
        return this.connString;
    }
    
    public void setConnString(String connString) {
        this.connString = connString;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getDbtype() {
        return this.dbtype;
    }
    
    public void setDbtype(String dbtype) {
        this.dbtype = dbtype;
    }

    public byte[] getHibernateMapping() {
        return this.hibernateMapping;
    }
    
    public void setHibernateMapping(byte[] hibernateMapping) {
        this.hibernateMapping = hibernateMapping;
    }
   








}
