package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4



/**
 * DcTipoeColumn generated by hbm2java
 */

public class DcTipoeColumn  implements java.io.Serializable {


    // Fields    

     private Long id;
     private DcTipoe dcTipoe;
     private DcColumn dcColumn;


    // Constructors

    /** default constructor */
    public DcTipoeColumn() {
    }

    
    /** full constructor */
    public DcTipoeColumn(Long id, DcTipoe dcTipoe, DcColumn dcColumn) {
        this.id = id;
        this.dcTipoe = dcTipoe;
        this.dcColumn = dcColumn;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public DcTipoe getDcTipoe() {
        return this.dcTipoe;
    }
    
    public void setDcTipoe(DcTipoe dcTipoe) {
        this.dcTipoe = dcTipoe;
    }

    public DcColumn getDcColumn() {
        return this.dcColumn;
    }
    
    public void setDcColumn(DcColumn dcColumn) {
        this.dcColumn = dcColumn;
    }
   








}
