package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4



/**
 * DvFormatClasse generated by hbm2java
 */

public class DvFormatClasse  implements java.io.Serializable {


    // Fields    

     private DvFormatClasseId id;
     private DvUserEntity dvUserEntity;
     private DvClasse dvClasse;
     private byte[] filter;
     private byte[] list;
     private byte[] detail;


    // Constructors

    /** default constructor */
    public DvFormatClasse() {
    }

	/** minimal constructor */
    public DvFormatClasse(DvFormatClasseId id, DvUserEntity dvUserEntity, DvClasse dvClasse) {
        this.id = id;
        this.dvUserEntity = dvUserEntity;
        this.dvClasse = dvClasse;
    }
    
    /** full constructor */
    public DvFormatClasse(DvFormatClasseId id, DvUserEntity dvUserEntity, DvClasse dvClasse, byte[] filter, byte[] list, byte[] detail) {
        this.id = id;
        this.dvUserEntity = dvUserEntity;
        this.dvClasse = dvClasse;
        this.filter = filter;
        this.list = list;
        this.detail = detail;
    }
    

   
    // Property accessors

    public DvFormatClasseId getId() {
        return this.id;
    }
    
    public void setId(DvFormatClasseId id) {
        this.id = id;
    }

    public DvUserEntity getDvUserEntity() {
        return this.dvUserEntity;
    }
    
    public void setDvUserEntity(DvUserEntity dvUserEntity) {
        this.dvUserEntity = dvUserEntity;
    }

    public DvClasse getDvClasse() {
        return this.dvClasse;
    }
    
    public void setDvClasse(DvClasse dvClasse) {
        this.dvClasse = dvClasse;
    }

    public byte[] getFilter() {
        return this.filter;
    }
    
    public void setFilter(byte[] filter) {
        this.filter = filter;
    }

    public byte[] getList() {
        return this.list;
    }
    
    public void setList(byte[] list) {
        this.list = list;
    }

    public byte[] getDetail() {
        return this.detail;
    }
    
    public void setDetail(byte[] detail) {
        this.detail = detail;
    }
   








}
