package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.28 by Hibernate Tools 3.1.0.beta4



/**
 * DvFormatClasseId generated by hbm2java
 */

public class DvFormatClasseId  implements java.io.Serializable {


    // Fields    

     private Long fkDvUserEntity;
     private long fkDvClasse;


    // Constructors

    /** default constructor */
    public DvFormatClasseId() {
    }

    
    /** full constructor */
    public DvFormatClasseId(Long fkDvUserEntity, long fkDvClasse) {
        this.fkDvUserEntity = fkDvUserEntity;
        this.fkDvClasse = fkDvClasse;
    }
    

   
    // Property accessors

    public Long getFkDvUserEntity() {
        return this.fkDvUserEntity;
    }
    
    public void setFkDvUserEntity(Long fkDvUserEntity) {
        this.fkDvUserEntity = fkDvUserEntity;
    }

    public long getFkDvClasse() {
        return this.fkDvClasse;
    }
    
    public void setFkDvClasse(long fkDvClasse) {
        this.fkDvClasse = fkDvClasse;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DvFormatClasseId) ) return false;
		 DvFormatClasseId castOther = ( DvFormatClasseId ) other; 
         
		 return ( (this.getFkDvUserEntity()==castOther.getFkDvUserEntity()) || ( this.getFkDvUserEntity()!=null && castOther.getFkDvUserEntity()!=null && this.getFkDvUserEntity().equals(castOther.getFkDvUserEntity()) ) )
 && (this.getFkDvClasse()==castOther.getFkDvClasse());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFkDvUserEntity() == null ? 0 : this.getFkDvUserEntity().hashCode() );
         result = 37 * result + (int) this.getFkDvClasse();
         return result;
   }   





}
