package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.26 by Hibernate Tools 3.1.0.beta4



/**
 * DvKey generated by hbm2java
 */

public class DvKey  implements java.io.Serializable {


    // Fields    

     private Long id;
     private DcEntity dcEntity;
     private String entityKey;


    // Constructors

    /** default constructor */
    public DvKey() {
    }

	/** minimal constructor */
    public DvKey(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public DvKey(Long id, DcEntity dcEntity, String entityKey) {
        this.id = id;
        this.dcEntity = dcEntity;
        this.entityKey = entityKey;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public DcEntity getDcEntity() {
        return this.dcEntity;
    }
    
    public void setDcEntity(DcEntity dcEntity) {
        this.dcEntity = dcEntity;
    }

    public String getEntityKey() {
        return this.entityKey;
    }
    
    public void setEntityKey(String entityKey) {
        this.entityKey = entityKey;
    }
   








}
