package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * DvProgetto generated by hbm2java
 */

public class DvProgetto  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String name;
     private Long sortOrder;
     private Set dvClasses = new HashSet(0);


    // Constructors

    /** default constructor */
    public DvProgetto() {
    }

	/** minimal constructor */
    public DvProgetto(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public DvProgetto(Long id, String name, Long sortOrder, Set dvClasses) {
        this.id = id;
        this.name = name;
        this.sortOrder = sortOrder;
        this.dvClasses = dvClasses;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Long getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(Long sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Set getDvClasses() {
        return this.dvClasses;
    }
    
    public void setDvClasses(Set dvClasses) {
        this.dvClasses = dvClasses;
    }
   








}
