package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.27 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * DvTema generated by hbm2java
 */

public class DvTema  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String name;
     private Set dcTipoes = new HashSet(0);


    // Constructors

    /** default constructor */
    public DvTema() {
    }

	/** minimal constructor */
    public DvTema(Long id, String name) {
        this.id = id;
        this.name = name;
    }
    
    /** full constructor */
    public DvTema(Long id, String name, Set dcTipoes) {
        this.id = id;
        this.name = name;
        this.dcTipoes = dcTipoes;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getDcTipoes() {
        return this.dcTipoes;
    }
    
    public void setDcTipoes(Set dcTipoes) {
        this.dcTipoes = dcTipoes;
    }
   








}
