package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.28 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * DvUeFromEntity generated by hbm2java
 */

public class DvUeFromEntity  implements java.io.Serializable {


    // Fields    

     private Long id;
     private DcEntity dcEntity;
     private DvUserEntity dvUserEntity;
     private String alias;
     private Set dcFromRelsForFkDvEuFrom2 = new HashSet(0);
     private Set dcFromRelsForFkDvEuFrom1 = new HashSet(0);


    // Constructors

    /** default constructor */
    public DvUeFromEntity() {
    }

	/** minimal constructor */
    public DvUeFromEntity(Long id) {
        this.id = id;
    }
    
    /** full constructor */
    public DvUeFromEntity(Long id, DcEntity dcEntity, DvUserEntity dvUserEntity, String alias, Set dcFromRelsForFkDvEuFrom2, Set dcFromRelsForFkDvEuFrom1) {
        this.id = id;
        this.dcEntity = dcEntity;
        this.dvUserEntity = dvUserEntity;
        this.alias = alias;
        this.dcFromRelsForFkDvEuFrom2 = dcFromRelsForFkDvEuFrom2;
        this.dcFromRelsForFkDvEuFrom1 = dcFromRelsForFkDvEuFrom1;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public DcEntity getDcEntity() {
        return this.dcEntity;
    }
    
    public void setDcEntity(DcEntity dcEntity) {
        this.dcEntity = dcEntity;
    }

    public DvUserEntity getDvUserEntity() {
        return this.dvUserEntity;
    }
    
    public void setDvUserEntity(DvUserEntity dvUserEntity) {
        this.dvUserEntity = dvUserEntity;
    }

    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Set getDcFromRelsForFkDvEuFrom2() {
        return this.dcFromRelsForFkDvEuFrom2;
    }
    
    public void setDcFromRelsForFkDvEuFrom2(Set dcFromRelsForFkDvEuFrom2) {
        this.dcFromRelsForFkDvEuFrom2 = dcFromRelsForFkDvEuFrom2;
    }

    public Set getDcFromRelsForFkDvEuFrom1() {
        return this.dcFromRelsForFkDvEuFrom1;
    }
    
    public void setDcFromRelsForFkDvEuFrom1(Set dcFromRelsForFkDvEuFrom1) {
        this.dcFromRelsForFkDvEuFrom1 = dcFromRelsForFkDvEuFrom1;
    }
   








}
