package it.webred.diogene.db.model;
// Generated 22-nov-2007 11.42.28 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * DvUserEntity generated by hbm2java
 */

public class DvUserEntity  implements java.io.Serializable {


    // Fields    

     private Long id;
     private DcRel dcRel;
     private DcEntity dcEntity;
     private String predicate;
     private byte[] sqlStatement;
     private byte[] sqlStatementBk;
     private Set dvFormatClasses = new HashSet(0);
     private Set dvUeFromEntities = new HashSet(0);
     private Set dvUeOrders = new HashSet(0);
     private Set dvUeGroups = new HashSet(0);


    // Constructors

    /** default constructor */
    public DvUserEntity() {
    }

	/** minimal constructor */
    public DvUserEntity(Long id, byte[] sqlStatement) {
        this.id = id;
        this.sqlStatement = sqlStatement;
    }
    
    /** full constructor */
    public DvUserEntity(Long id, DcRel dcRel, DcEntity dcEntity, String predicate, byte[] sqlStatement, byte[] sqlStatementBk, Set dvFormatClasses, Set dvUeFromEntities, Set dvUeOrders, Set dvUeGroups) {
        this.id = id;
        this.dcRel = dcRel;
        this.dcEntity = dcEntity;
        this.predicate = predicate;
        this.sqlStatement = sqlStatement;
        this.sqlStatementBk = sqlStatementBk;
        this.dvFormatClasses = dvFormatClasses;
        this.dvUeFromEntities = dvUeFromEntities;
        this.dvUeOrders = dvUeOrders;
        this.dvUeGroups = dvUeGroups;
    }
    

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public DcRel getDcRel() {
        return this.dcRel;
    }
    
    public void setDcRel(DcRel dcRel) {
        this.dcRel = dcRel;
    }

    public DcEntity getDcEntity() {
        return this.dcEntity;
    }
    
    public void setDcEntity(DcEntity dcEntity) {
        this.dcEntity = dcEntity;
    }

    public String getPredicate() {
        return this.predicate;
    }
    
    public void setPredicate(String predicate) {
        this.predicate = predicate;
    }

    public byte[] getSqlStatement() {
        return this.sqlStatement;
    }
    
    public void setSqlStatement(byte[] sqlStatement) {
        this.sqlStatement = sqlStatement;
    }

    public byte[] getSqlStatementBk() {
        return this.sqlStatementBk;
    }
    
    public void setSqlStatementBk(byte[] sqlStatementBk) {
        this.sqlStatementBk = sqlStatementBk;
    }

    public Set getDvFormatClasses() {
        return this.dvFormatClasses;
    }
    
    public void setDvFormatClasses(Set dvFormatClasses) {
        this.dvFormatClasses = dvFormatClasses;
    }

    public Set getDvUeFromEntities() {
        return this.dvUeFromEntities;
    }
    
    public void setDvUeFromEntities(Set dvUeFromEntities) {
        this.dvUeFromEntities = dvUeFromEntities;
    }

    public Set getDvUeOrders() {
        return this.dvUeOrders;
    }
    
    public void setDvUeOrders(Set dvUeOrders) {
        this.dvUeOrders = dvUeOrders;
    }

    public Set getDvUeGroups() {
        return this.dvUeGroups;
    }
    
    public void setDvUeGroups(Set dvUeGroups) {
        this.dvUeGroups = dvUeGroups;
    }
   








}
