//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.04 at 03:21:53 PM CET 
//


package it.webred.ct.service.jaxb.intTerritorio.datiCivico.request;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datiCivico element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="datiCivico">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="infoUtente" type="{}userInfo" minOccurs="0"/>
 *           &lt;element name="richiesta" type="{}richiesta" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infoUtente",
    "richiesta"
})
@XmlRootElement(name = "datiCivico")
public class DatiCivico
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected UserInfo infoUtente;
    protected Richiesta richiesta;

    /**
     * Gets the value of the infoUtente property.
     * 
     * @return
     *     possible object is
     *     {@link UserInfo }
     *     
     */
    public UserInfo getInfoUtente() {
        return infoUtente;
    }

    /**
     * Sets the value of the infoUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInfo }
     *     
     */
    public void setInfoUtente(UserInfo value) {
        this.infoUtente = value;
    }

    public boolean isSetInfoUtente() {
        return (this.infoUtente!= null);
    }

    /**
     * Gets the value of the richiesta property.
     * 
     * @return
     *     possible object is
     *     {@link Richiesta }
     *     
     */
    public Richiesta getRichiesta() {
        return richiesta;
    }

    /**
     * Sets the value of the richiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Richiesta }
     *     
     */
    public void setRichiesta(Richiesta value) {
        this.richiesta = value;
    }

    public boolean isSetRichiesta() {
        return (this.richiesta!= null);
    }

}
