CREATE UNIQUE INDEX FK_AM_PERMISSION_AIR ON AM_PERMISSION_AIR (FK_AM_PERMISSION, FK_AM_AI_ROLE);
CREATE UNIQUE INDEX FK_AM_GROUP_AIR ON AM_GROUP_AIR (FK_AM_GROUP, FK_AM_AI_ROLE);
CREATE UNIQUE INDEX FK_AM_AI_ROLE ON AM_AI_ROLE (FK_AM_ROLE, FK_AM_APPLICATION_ITEM);
CREATE UNIQUE INDEX FK_AM_APPLICATION_ITEM ON AM_APPLICATION_ITEM (FK_AM_APPLICATION, FK_AM_ITEM );
CREATE UNIQUE INDEX FK_AM_USER_AIR ON AM_USER_AIR (FK_AM_USER, FK_AM_AI_ROLE);
CREATE UNIQUE INDEX FK_AM_USER_GROUP ON AM_USER_GROUP (FK_AM_USER, FK_AM_GROUP);


