//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 12:57:11 PM CEST 
//


package it.webred.ct.service.jaxb.verificaCoordinate.response;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datiAttesi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datiAttesi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datiAttesiResidenziale" type="{}datiAttesiResidenziale" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="datiAttesiNonResidenziale" type="{}datiAttesiNonResidenziale" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datiAttesi", propOrder = {
    "datiAttesiResidenziale",
    "datiAttesiNonResidenziale"
})
public class DatiAttesi
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected List<DatiAttesiResidenziale> datiAttesiResidenziale;
    @XmlElement(required = true)
    protected List<DatiAttesiNonResidenziale> datiAttesiNonResidenziale;

    /**
     * Gets the value of the datiAttesiResidenziale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiAttesiResidenziale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatiAttesiResidenziale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatiAttesiResidenziale }
     * 
     * 
     */
    public List<DatiAttesiResidenziale> getDatiAttesiResidenziale() {
        if (datiAttesiResidenziale == null) {
            datiAttesiResidenziale = new ArrayList<DatiAttesiResidenziale>();
        }
        return this.datiAttesiResidenziale;
    }

    public boolean isSetDatiAttesiResidenziale() {
        return ((this.datiAttesiResidenziale!= null)&&(!this.datiAttesiResidenziale.isEmpty()));
    }

    public void unsetDatiAttesiResidenziale() {
        this.datiAttesiResidenziale = null;
    }

    /**
     * Gets the value of the datiAttesiNonResidenziale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiAttesiNonResidenziale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatiAttesiNonResidenziale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatiAttesiNonResidenziale }
     * 
     * 
     */
    public List<DatiAttesiNonResidenziale> getDatiAttesiNonResidenziale() {
        if (datiAttesiNonResidenziale == null) {
            datiAttesiNonResidenziale = new ArrayList<DatiAttesiNonResidenziale>();
        }
        return this.datiAttesiNonResidenziale;
    }

    public boolean isSetDatiAttesiNonResidenziale() {
        return ((this.datiAttesiNonResidenziale!= null)&&(!this.datiAttesiNonResidenziale.isEmpty()));
    }

    public void unsetDatiAttesiNonResidenziale() {
        this.datiAttesiNonResidenziale = null;
    }

}
