//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 12:57:11 PM CEST 
//


package it.webred.ct.service.jaxb.verificaCoordinate.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.webred.ct.service.jaxb.verificaCoordinate.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.webred.ct.service.jaxb.verificaCoordinate.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link DestFunzionale }
     * 
     */
    public DestFunzionale createDestFunzionale() {
        return new DestFunzionale();
    }

    /**
     * Create an instance of {@link Ok }
     * 
     */
    public Ok createOk() {
        return new Ok();
    }

    /**
     * Create an instance of {@link Uiu }
     * 
     */
    public Uiu createUiu() {
        return new Uiu();
    }

    /**
     * Create an instance of {@link ZonaDecentramento }
     * 
     */
    public ZonaDecentramento createZonaDecentramento() {
        return new ZonaDecentramento();
    }

    /**
     * Create an instance of {@link AttributoType }
     * 
     */
    public AttributoType createAttributoType() {
        return new AttributoType();
    }

    /**
     * Create an instance of {@link Graf }
     * 
     */
    public Graf createGraf() {
        return new Graf();
    }

    /**
     * Create an instance of {@link Coordinate }
     * 
     */
    public Coordinate createCoordinate() {
        return new Coordinate();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link VerificaCoordinate }
     * 
     */
    public VerificaCoordinate createVerificaCoordinate() {
        return new VerificaCoordinate();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ClassiMaxCategoria }
     * 
     */
    public ClassiMaxCategoria createClassiMaxCategoria() {
        return new ClassiMaxCategoria();
    }

    /**
     * Create an instance of {@link Via }
     * 
     */
    public Via createVia() {
        return new Via();
    }

    /**
     * Create an instance of {@link VincoloType }
     * 
     */
    public VincoloType createVincoloType() {
        return new VincoloType();
    }

    /**
     * Create an instance of {@link DatiAttesiNonResidenziale }
     * 
     */
    public DatiAttesiNonResidenziale createDatiAttesiNonResidenziale() {
        return new DatiAttesiNonResidenziale();
    }

    /**
     * Create an instance of {@link ZonaOmogenea }
     * 
     */
    public ZonaOmogenea createZonaOmogenea() {
        return new ZonaOmogenea();
    }

    /**
     * Create an instance of {@link ElencoUiu }
     * 
     */
    public ElencoUiu createElencoUiu() {
        return new ElencoUiu();
    }

    /**
     * Create an instance of {@link DatiAttesi }
     * 
     */
    public DatiAttesi createDatiAttesi() {
        return new DatiAttesi();
    }

    /**
     * Create an instance of {@link Mappale }
     * 
     */
    public Mappale createMappale() {
        return new Mappale();
    }

    /**
     * Create an instance of {@link ElencoVie }
     * 
     */
    public ElencoVie createElencoVie() {
        return new ElencoVie();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link ElencoMappale }
     * 
     */
    public ElencoMappale createElencoMappale() {
        return new ElencoMappale();
    }

    /**
     * Create an instance of {@link Classamento }
     * 
     */
    public Classamento createClassamento() {
        return new Classamento();
    }

    /**
     * Create an instance of {@link DatiAttesiResidenziale }
     * 
     */
    public DatiAttesiResidenziale createDatiAttesiResidenziale() {
        return new DatiAttesiResidenziale();
    }

    /**
     * Create an instance of {@link VincoliType }
     * 
     */
    public VincoliType createVincoliType() {
        return new VincoliType();
    }

    /**
     * Create an instance of {@link ElencoCivico }
     * 
     */
    public ElencoCivico createElencoCivico() {
        return new ElencoCivico();
    }

    /**
     * Create an instance of {@link DatiPrg }
     * 
     */
    public DatiPrg createDatiPrg() {
        return new DatiPrg();
    }

    /**
     * Create an instance of {@link RigaType }
     * 
     */
    public RigaType createRigaType() {
        return new RigaType();
    }

    /**
     * Create an instance of {@link Classamenti }
     * 
     */
    public Classamenti createClassamenti() {
        return new Classamenti();
    }

    /**
     * Create an instance of {@link Prg }
     * 
     */
    public Prg createPrg() {
        return new Prg();
    }

    /**
     * Create an instance of {@link CommonUserInfo }
     * 
     */
    public CommonUserInfo createCommonUserInfo() {
        return new CommonUserInfo();
    }

    /**
     * Create an instance of {@link ClasseMaxCategoria }
     * 
     */
    public ClasseMaxCategoria createClasseMaxCategoria() {
        return new ClasseMaxCategoria();
    }

    /**
     * Create an instance of {@link Civico }
     * 
     */
    public Civico createCivico() {
        return new Civico();
    }

}
