//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.05 at 12:57:11 PM CEST 
//


package it.webred.ct.service.jaxb.verificaCoordinate.response;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for verificaCoordinate element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="verificaCoordinate">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="infoUtente" type="{}userInfo" minOccurs="0"/>
 *           &lt;element name="error" type="{}error" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="ok" type="{}ok" minOccurs="0"/>
 *           &lt;element name="info" type="{}info" minOccurs="0"/>
 *           &lt;element name="elencoVie" type="{}elencoVie" minOccurs="0"/>
 *           &lt;element name="elencoUiu" type="{}elencoUiu" minOccurs="0"/>
 *           &lt;element name="elencoCivico" type="{}elencoCivico" minOccurs="0"/>
 *           &lt;element name="elencoMappale" type="{}elencoMappale" minOccurs="0"/>
 *           &lt;element name="graf" type="{}graf" minOccurs="0"/>
 *           &lt;element name="coordinate" type="{}coordinate" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infoUtente",
    "error",
    "ok",
    "info",
    "elencoVie",
    "elencoUiu",
    "elencoCivico",
    "elencoMappale",
    "graf",
    "coordinate"
})
@XmlRootElement(name = "verificaCoordinate")
public class VerificaCoordinate
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected UserInfo infoUtente;
    @XmlElement(required = true)
    protected List<Error> error;
    protected Ok ok;
    protected Info info;
    protected ElencoVie elencoVie;
    protected ElencoUiu elencoUiu;
    protected ElencoCivico elencoCivico;
    protected ElencoMappale elencoMappale;
    protected Graf graf;
    protected Coordinate coordinate;
    @XmlAttribute
    protected String tipo;

    /**
     * Gets the value of the infoUtente property.
     * 
     * @return
     *     possible object is
     *     {@link UserInfo }
     *     
     */
    public UserInfo getInfoUtente() {
        return infoUtente;
    }

    /**
     * Sets the value of the infoUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInfo }
     *     
     */
    public void setInfoUtente(UserInfo value) {
        this.infoUtente = value;
    }

    public boolean isSetInfoUtente() {
        return (this.infoUtente!= null);
    }

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Error }
     * 
     * 
     */
    public List<Error> getError() {
        if (error == null) {
            error = new ArrayList<Error>();
        }
        return this.error;
    }

    public boolean isSetError() {
        return ((this.error!= null)&&(!this.error.isEmpty()));
    }

    public void unsetError() {
        this.error = null;
    }

    /**
     * Gets the value of the ok property.
     * 
     * @return
     *     possible object is
     *     {@link Ok }
     *     
     */
    public Ok getOk() {
        return ok;
    }

    /**
     * Sets the value of the ok property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ok }
     *     
     */
    public void setOk(Ok value) {
        this.ok = value;
    }

    public boolean isSetOk() {
        return (this.ok!= null);
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link Info }
     *     
     */
    public Info getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link Info }
     *     
     */
    public void setInfo(Info value) {
        this.info = value;
    }

    public boolean isSetInfo() {
        return (this.info!= null);
    }

    /**
     * Gets the value of the elencoVie property.
     * 
     * @return
     *     possible object is
     *     {@link ElencoVie }
     *     
     */
    public ElencoVie getElencoVie() {
        return elencoVie;
    }

    /**
     * Sets the value of the elencoVie property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElencoVie }
     *     
     */
    public void setElencoVie(ElencoVie value) {
        this.elencoVie = value;
    }

    public boolean isSetElencoVie() {
        return (this.elencoVie!= null);
    }

    /**
     * Gets the value of the elencoUiu property.
     * 
     * @return
     *     possible object is
     *     {@link ElencoUiu }
     *     
     */
    public ElencoUiu getElencoUiu() {
        return elencoUiu;
    }

    /**
     * Sets the value of the elencoUiu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElencoUiu }
     *     
     */
    public void setElencoUiu(ElencoUiu value) {
        this.elencoUiu = value;
    }

    public boolean isSetElencoUiu() {
        return (this.elencoUiu!= null);
    }

    /**
     * Gets the value of the elencoCivico property.
     * 
     * @return
     *     possible object is
     *     {@link ElencoCivico }
     *     
     */
    public ElencoCivico getElencoCivico() {
        return elencoCivico;
    }

    /**
     * Sets the value of the elencoCivico property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElencoCivico }
     *     
     */
    public void setElencoCivico(ElencoCivico value) {
        this.elencoCivico = value;
    }

    public boolean isSetElencoCivico() {
        return (this.elencoCivico!= null);
    }

    /**
     * Gets the value of the elencoMappale property.
     * 
     * @return
     *     possible object is
     *     {@link ElencoMappale }
     *     
     */
    public ElencoMappale getElencoMappale() {
        return elencoMappale;
    }

    /**
     * Sets the value of the elencoMappale property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElencoMappale }
     *     
     */
    public void setElencoMappale(ElencoMappale value) {
        this.elencoMappale = value;
    }

    public boolean isSetElencoMappale() {
        return (this.elencoMappale!= null);
    }

    /**
     * Gets the value of the graf property.
     * 
     * @return
     *     possible object is
     *     {@link Graf }
     *     
     */
    public Graf getGraf() {
        return graf;
    }

    /**
     * Sets the value of the graf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Graf }
     *     
     */
    public void setGraf(Graf value) {
        this.graf = value;
    }

    public boolean isSetGraf() {
        return (this.graf!= null);
    }

    /**
     * Gets the value of the coordinate property.
     * 
     * @return
     *     possible object is
     *     {@link Coordinate }
     *     
     */
    public Coordinate getCoordinate() {
        return coordinate;
    }

    /**
     * Sets the value of the coordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coordinate }
     *     
     */
    public void setCoordinate(Coordinate value) {
        this.coordinate = value;
    }

    public boolean isSetCoordinate() {
        return (this.coordinate!= null);
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    public boolean isSetTipo() {
        return (this.tipo!= null);
    }

}
