package it.webred.mui.model;
// Generated 1-apr-2009 13.23.53 by Hibernate Tools 3.1.0.beta4



/**
 * CodiceBelfiore generated by hbm2java
 */

public class CodiceBelfiore  implements java.io.Serializable {


    // Fields    

     private String codice;
     private String descrizione;


    // Constructors

    /** default constructor */
    public CodiceBelfiore() {
    }

    
    /** full constructor */
    public CodiceBelfiore(String codice, String descrizione) {
        this.codice = codice;
        this.descrizione = descrizione;
    }
    

   
    // Property accessors

    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }

    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
   








}
