package it.webred.mui.model;
// Generated 1-apr-2009 13.23.54 by Hibernate Tools 3.1.0.beta4



/**
 * CodiceErroreImportBase generated by hbm2java
 */

public class CodiceErroreImportBase  implements java.io.Serializable {


    // Fields    

     private String codiceRegolaInfranta;
     private String descrizione;
     private Integer classe;
     private Boolean flagBloccante;
     private String effetto;


    // Constructors

    /** default constructor */
    public CodiceErroreImportBase() {
    }

	/** minimal constructor */
    public CodiceErroreImportBase(String codiceRegolaInfranta, Integer classe) {
        this.codiceRegolaInfranta = codiceRegolaInfranta;
        this.classe = classe;
    }
    
    /** full constructor */
    public CodiceErroreImportBase(String codiceRegolaInfranta, String descrizione, Integer classe, Boolean flagBloccante, String effetto) {
        this.codiceRegolaInfranta = codiceRegolaInfranta;
        this.descrizione = descrizione;
        this.classe = classe;
        this.flagBloccante = flagBloccante;
        this.effetto = effetto;
    }
    

   
    // Property accessors

    public String getCodiceRegolaInfranta() {
        return this.codiceRegolaInfranta;
    }
    
    public void setCodiceRegolaInfranta(String codiceRegolaInfranta) {
        this.codiceRegolaInfranta = codiceRegolaInfranta;
    }

    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public Integer getClasse() {
        return this.classe;
    }
    
    public void setClasse(Integer classe) {
        this.classe = classe;
    }

    public Boolean getFlagBloccante() {
        return this.flagBloccante;
    }
    
    public void setFlagBloccante(Boolean flagBloccante) {
        this.flagBloccante = flagBloccante;
    }

    public String getEffetto() {
        return this.effetto;
    }
    
    public void setEffetto(String effetto) {
        this.effetto = effetto;
    }
   








}
