package it.webred.mui.model;
// Generated 1-apr-2009 13.23.56 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MiConsComunicazione generated by hbm2java
 */

public class MiConsComunicazione  implements java.io.Serializable {


    // Fields    

     private long iid;
     private MiDupSoggetti miDupSoggetti;
     private MiDupNotaTras miDupNotaTras;
     private MiDupFornitura miDupFornitura;
     private String codiceFiscale;
     private String prefisso;
     private String telefono;
     private String cognome;
     private String nome;
     private Date dataNascita;
     private String comuneNascita;
     private String provinciaNascita;
     private String sesso;
     private String indirizzo;
     private String cap;
     private String comune;
     private String provincia;
     private String indirizzoDomicilio;
     private String capDomicilio;
     private String comuneDomicilio;
     private String provinciaDomicilio;
     private String codiceFiscaleRL;
     private String prefissoRL;
     private String telefonoRL;
     private String cognomeRL;
     private String nomeRL;
     private Date dataNascitaRL;
     private String comuneNascitaRL;
     private String provinciaNascitaRL;
     private String sessoRL;
     private String indirizzoRL;
     private String capRL;
     private String comuneRL;
     private String provinciaRL;
     private String indirizzoDomicilioRL;
     private String capDomicilioRL;
     private String comuneDomicilioRL;
     private String provinciaDomicilioRL;
     private Boolean flagRappresentanteLegale;
     private Boolean flagCuratoreFallimentare;
     private Boolean flagTutore;
     private Boolean flagErede;
     private String altraNatura;
     private Date dataComunicazione;
     private Integer stato;
     private Set<MiConsOggetto> miConsOggettos = new HashSet<MiConsOggetto>(0);


    // Constructors

    /** default constructor */
    public MiConsComunicazione() {
    }

	/** minimal constructor */
    public MiConsComunicazione(MiDupSoggetti miDupSoggetti, MiDupNotaTras miDupNotaTras, MiDupFornitura miDupFornitura) {
        this.miDupSoggetti = miDupSoggetti;
        this.miDupNotaTras = miDupNotaTras;
        this.miDupFornitura = miDupFornitura;
    }
    
    /** full constructor */
    public MiConsComunicazione(MiDupSoggetti miDupSoggetti, MiDupNotaTras miDupNotaTras, MiDupFornitura miDupFornitura, String codiceFiscale, String prefisso, String telefono, String cognome, String nome, Date dataNascita, String comuneNascita, String provinciaNascita, String sesso, String indirizzo, String cap, String comune, String provincia, String indirizzoDomicilio, String capDomicilio, String comuneDomicilio, String provinciaDomicilio, String codiceFiscaleRL, String prefissoRL, String telefonoRL, String cognomeRL, String nomeRL, Date dataNascitaRL, String comuneNascitaRL, String provinciaNascitaRL, String sessoRL, String indirizzoRL, String capRL, String comuneRL, String provinciaRL, String indirizzoDomicilioRL, String capDomicilioRL, String comuneDomicilioRL, String provinciaDomicilioRL, Boolean flagRappresentanteLegale, Boolean flagCuratoreFallimentare, Boolean flagTutore, Boolean flagErede, String altraNatura, Date dataComunicazione, Integer stato, Set<MiConsOggetto> miConsOggettos) {
        this.miDupSoggetti = miDupSoggetti;
        this.miDupNotaTras = miDupNotaTras;
        this.miDupFornitura = miDupFornitura;
        this.codiceFiscale = codiceFiscale;
        this.prefisso = prefisso;
        this.telefono = telefono;
        this.cognome = cognome;
        this.nome = nome;
        this.dataNascita = dataNascita;
        this.comuneNascita = comuneNascita;
        this.provinciaNascita = provinciaNascita;
        this.sesso = sesso;
        this.indirizzo = indirizzo;
        this.cap = cap;
        this.comune = comune;
        this.provincia = provincia;
        this.indirizzoDomicilio = indirizzoDomicilio;
        this.capDomicilio = capDomicilio;
        this.comuneDomicilio = comuneDomicilio;
        this.provinciaDomicilio = provinciaDomicilio;
        this.codiceFiscaleRL = codiceFiscaleRL;
        this.prefissoRL = prefissoRL;
        this.telefonoRL = telefonoRL;
        this.cognomeRL = cognomeRL;
        this.nomeRL = nomeRL;
        this.dataNascitaRL = dataNascitaRL;
        this.comuneNascitaRL = comuneNascitaRL;
        this.provinciaNascitaRL = provinciaNascitaRL;
        this.sessoRL = sessoRL;
        this.indirizzoRL = indirizzoRL;
        this.capRL = capRL;
        this.comuneRL = comuneRL;
        this.provinciaRL = provinciaRL;
        this.indirizzoDomicilioRL = indirizzoDomicilioRL;
        this.capDomicilioRL = capDomicilioRL;
        this.comuneDomicilioRL = comuneDomicilioRL;
        this.provinciaDomicilioRL = provinciaDomicilioRL;
        this.flagRappresentanteLegale = flagRappresentanteLegale;
        this.flagCuratoreFallimentare = flagCuratoreFallimentare;
        this.flagTutore = flagTutore;
        this.flagErede = flagErede;
        this.altraNatura = altraNatura;
        this.dataComunicazione = dataComunicazione;
        this.stato = stato;
        this.miConsOggettos = miConsOggettos;
    }
    

   
    // Property accessors

    public long getIid() {
        return this.iid;
    }
    
    public void setIid(long iid) {
        this.iid = iid;
    }

    public MiDupSoggetti getMiDupSoggetti() {
        return this.miDupSoggetti;
    }
    
    public void setMiDupSoggetti(MiDupSoggetti miDupSoggetti) {
        this.miDupSoggetti = miDupSoggetti;
    }

    public MiDupNotaTras getMiDupNotaTras() {
        return this.miDupNotaTras;
    }
    
    public void setMiDupNotaTras(MiDupNotaTras miDupNotaTras) {
        this.miDupNotaTras = miDupNotaTras;
    }

    public MiDupFornitura getMiDupFornitura() {
        return this.miDupFornitura;
    }
    
    public void setMiDupFornitura(MiDupFornitura miDupFornitura) {
        this.miDupFornitura = miDupFornitura;
    }

    public String getCodiceFiscale() {
        return this.codiceFiscale;
    }
    
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    public String getPrefisso() {
        return this.prefisso;
    }
    
    public void setPrefisso(String prefisso) {
        this.prefisso = prefisso;
    }

    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public Date getDataNascita() {
        return this.dataNascita;
    }
    
    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    public String getComuneNascita() {
        return this.comuneNascita;
    }
    
    public void setComuneNascita(String comuneNascita) {
        this.comuneNascita = comuneNascita;
    }

    public String getProvinciaNascita() {
        return this.provinciaNascita;
    }
    
    public void setProvinciaNascita(String provinciaNascita) {
        this.provinciaNascita = provinciaNascita;
    }

    public String getSesso() {
        return this.sesso;
    }
    
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    public String getIndirizzo() {
        return this.indirizzo;
    }
    
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    public String getCap() {
        return this.cap;
    }
    
    public void setCap(String cap) {
        this.cap = cap;
    }

    public String getComune() {
        return this.comune;
    }
    
    public void setComune(String comune) {
        this.comune = comune;
    }

    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getIndirizzoDomicilio() {
        return this.indirizzoDomicilio;
    }
    
    public void setIndirizzoDomicilio(String indirizzoDomicilio) {
        this.indirizzoDomicilio = indirizzoDomicilio;
    }

    public String getCapDomicilio() {
        return this.capDomicilio;
    }
    
    public void setCapDomicilio(String capDomicilio) {
        this.capDomicilio = capDomicilio;
    }

    public String getComuneDomicilio() {
        return this.comuneDomicilio;
    }
    
    public void setComuneDomicilio(String comuneDomicilio) {
        this.comuneDomicilio = comuneDomicilio;
    }

    public String getProvinciaDomicilio() {
        return this.provinciaDomicilio;
    }
    
    public void setProvinciaDomicilio(String provinciaDomicilio) {
        this.provinciaDomicilio = provinciaDomicilio;
    }

    public String getCodiceFiscaleRL() {
        return this.codiceFiscaleRL;
    }
    
    public void setCodiceFiscaleRL(String codiceFiscaleRL) {
        this.codiceFiscaleRL = codiceFiscaleRL;
    }

    public String getPrefissoRL() {
        return this.prefissoRL;
    }
    
    public void setPrefissoRL(String prefissoRL) {
        this.prefissoRL = prefissoRL;
    }

    public String getTelefonoRL() {
        return this.telefonoRL;
    }
    
    public void setTelefonoRL(String telefonoRL) {
        this.telefonoRL = telefonoRL;
    }

    public String getCognomeRL() {
        return this.cognomeRL;
    }
    
    public void setCognomeRL(String cognomeRL) {
        this.cognomeRL = cognomeRL;
    }

    public String getNomeRL() {
        return this.nomeRL;
    }
    
    public void setNomeRL(String nomeRL) {
        this.nomeRL = nomeRL;
    }

    public Date getDataNascitaRL() {
        return this.dataNascitaRL;
    }
    
    public void setDataNascitaRL(Date dataNascitaRL) {
        this.dataNascitaRL = dataNascitaRL;
    }

    public String getComuneNascitaRL() {
        return this.comuneNascitaRL;
    }
    
    public void setComuneNascitaRL(String comuneNascitaRL) {
        this.comuneNascitaRL = comuneNascitaRL;
    }

    public String getProvinciaNascitaRL() {
        return this.provinciaNascitaRL;
    }
    
    public void setProvinciaNascitaRL(String provinciaNascitaRL) {
        this.provinciaNascitaRL = provinciaNascitaRL;
    }

    public String getSessoRL() {
        return this.sessoRL;
    }
    
    public void setSessoRL(String sessoRL) {
        this.sessoRL = sessoRL;
    }

    public String getIndirizzoRL() {
        return this.indirizzoRL;
    }
    
    public void setIndirizzoRL(String indirizzoRL) {
        this.indirizzoRL = indirizzoRL;
    }

    public String getCapRL() {
        return this.capRL;
    }
    
    public void setCapRL(String capRL) {
        this.capRL = capRL;
    }

    public String getComuneRL() {
        return this.comuneRL;
    }
    
    public void setComuneRL(String comuneRL) {
        this.comuneRL = comuneRL;
    }

    public String getProvinciaRL() {
        return this.provinciaRL;
    }
    
    public void setProvinciaRL(String provinciaRL) {
        this.provinciaRL = provinciaRL;
    }

    public String getIndirizzoDomicilioRL() {
        return this.indirizzoDomicilioRL;
    }
    
    public void setIndirizzoDomicilioRL(String indirizzoDomicilioRL) {
        this.indirizzoDomicilioRL = indirizzoDomicilioRL;
    }

    public String getCapDomicilioRL() {
        return this.capDomicilioRL;
    }
    
    public void setCapDomicilioRL(String capDomicilioRL) {
        this.capDomicilioRL = capDomicilioRL;
    }

    public String getComuneDomicilioRL() {
        return this.comuneDomicilioRL;
    }
    
    public void setComuneDomicilioRL(String comuneDomicilioRL) {
        this.comuneDomicilioRL = comuneDomicilioRL;
    }

    public String getProvinciaDomicilioRL() {
        return this.provinciaDomicilioRL;
    }
    
    public void setProvinciaDomicilioRL(String provinciaDomicilioRL) {
        this.provinciaDomicilioRL = provinciaDomicilioRL;
    }

    public Boolean getFlagRappresentanteLegale() {
        return this.flagRappresentanteLegale;
    }
    
    public void setFlagRappresentanteLegale(Boolean flagRappresentanteLegale) {
        this.flagRappresentanteLegale = flagRappresentanteLegale;
    }

    public Boolean getFlagCuratoreFallimentare() {
        return this.flagCuratoreFallimentare;
    }
    
    public void setFlagCuratoreFallimentare(Boolean flagCuratoreFallimentare) {
        this.flagCuratoreFallimentare = flagCuratoreFallimentare;
    }

    public Boolean getFlagTutore() {
        return this.flagTutore;
    }
    
    public void setFlagTutore(Boolean flagTutore) {
        this.flagTutore = flagTutore;
    }

    public Boolean getFlagErede() {
        return this.flagErede;
    }
    
    public void setFlagErede(Boolean flagErede) {
        this.flagErede = flagErede;
    }

    public String getAltraNatura() {
        return this.altraNatura;
    }
    
    public void setAltraNatura(String altraNatura) {
        this.altraNatura = altraNatura;
    }

    public Date getDataComunicazione() {
        return this.dataComunicazione;
    }
    
    public void setDataComunicazione(Date dataComunicazione) {
        this.dataComunicazione = dataComunicazione;
    }

    public Integer getStato() {
        return this.stato;
    }
    
    public void setStato(Integer stato) {
        this.stato = stato;
    }

    public Set<MiConsOggetto> getMiConsOggettos() {
        return this.miConsOggettos;
    }
    
    public void setMiConsOggettos(Set<MiConsOggetto> miConsOggettos) {
        this.miConsOggettos = miConsOggettos;
    }
   








}
