package it.webred.mui.model;
// Generated 1-apr-2009 13.23.55 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MiDupFornituraBase generated by hbm2java
 */

public class MiDupFornituraBase  implements java.io.Serializable {


    // Fields    

     private long iid;
     private Date dataCaricamento;
     private String codiceFornitura;
     private String dataIniziale;
     private Date dataInizialeDate;
     private String dataFinale;
     private Date dataFinaleDate;
     private String dataPresAttoRet;
     private String dataEstrCons;
     private String dataEstrCata;
     private String fileLoadedNotParsed;
     private String fileTotNotParsed;
     private Set<MiDupSoggetti> miDupSoggettis = new HashSet<MiDupSoggetti>(0);
     private Set<MiDupFabbricatiIdentifica> miDupFabbricatiIdentificas = new HashSet<MiDupFabbricatiIdentifica>(0);
     private Set<MiDupTerreniInfo> miDupTerreniInfos = new HashSet<MiDupTerreniInfo>(0);
     private Set<MiDupFabbricatiInfo> miDupFabbricatiInfos = new HashSet<MiDupFabbricatiInfo>(0);
     private Set<MiDupIndirizziSog> miDupIndirizziSogs = new HashSet<MiDupIndirizziSog>(0);
     private Set<MiDupTitolarita> miDupTitolaritas = new HashSet<MiDupTitolarita>(0);
     private Set<MiDupNotaTras> miDupNotaTrases = new HashSet<MiDupNotaTras>(0);
     private Set<MiConsComunicazione> miConsComunicaziones = new HashSet<MiConsComunicazione>(0);
     private Set<MiQryFornitureLogDetail> miQryFornitureLogDetail = new HashSet<MiQryFornitureLogDetail>(0);
     private MiVwFornitureLogSummary miVwFornitureLogSummary;
     private MiVwNoteSummary miVwNoteSummary;
     private MiVwTitolariSummary miVwTitolariSummary;
     private MiVwComunicazioneSummary miVwComunicazioneSummary;
     private MiDupFornituraInfo miDupFornituraInfo;


    // Constructors

    /** default constructor */
    public MiDupFornituraBase() {
    }

	/** minimal constructor */
    public MiDupFornituraBase(Date dataCaricamento) {
        this.dataCaricamento = dataCaricamento;
    }
    
    /** full constructor */
    public MiDupFornituraBase(Date dataCaricamento, String codiceFornitura, String dataIniziale, Date dataInizialeDate, String dataFinale, Date dataFinaleDate, String dataPresAttoRet, String dataEstrCons, String dataEstrCata, String fileLoadedNotParsed, String fileTotNotParsed, Set<MiDupSoggetti> miDupSoggettis, Set<MiDupFabbricatiIdentifica> miDupFabbricatiIdentificas, Set<MiDupTerreniInfo> miDupTerreniInfos, Set<MiDupFabbricatiInfo> miDupFabbricatiInfos, Set<MiDupIndirizziSog> miDupIndirizziSogs, Set<MiDupTitolarita> miDupTitolaritas, Set<MiDupNotaTras> miDupNotaTrases, Set<MiConsComunicazione> miConsComunicaziones, Set<MiQryFornitureLogDetail> miQryFornitureLogDetail, MiVwFornitureLogSummary miVwFornitureLogSummary, MiVwNoteSummary miVwNoteSummary, MiVwTitolariSummary miVwTitolariSummary, MiVwComunicazioneSummary miVwComunicazioneSummary, MiDupFornituraInfo miDupFornituraInfo) {
        this.dataCaricamento = dataCaricamento;
        this.codiceFornitura = codiceFornitura;
        this.dataIniziale = dataIniziale;
        this.dataInizialeDate = dataInizialeDate;
        this.dataFinale = dataFinale;
        this.dataFinaleDate = dataFinaleDate;
        this.dataPresAttoRet = dataPresAttoRet;
        this.dataEstrCons = dataEstrCons;
        this.dataEstrCata = dataEstrCata;
        this.fileLoadedNotParsed = fileLoadedNotParsed;
        this.fileTotNotParsed = fileTotNotParsed;
        this.miDupSoggettis = miDupSoggettis;
        this.miDupFabbricatiIdentificas = miDupFabbricatiIdentificas;
        this.miDupTerreniInfos = miDupTerreniInfos;
        this.miDupFabbricatiInfos = miDupFabbricatiInfos;
        this.miDupIndirizziSogs = miDupIndirizziSogs;
        this.miDupTitolaritas = miDupTitolaritas;
        this.miDupNotaTrases = miDupNotaTrases;
        this.miConsComunicaziones = miConsComunicaziones;
        this.miQryFornitureLogDetail = miQryFornitureLogDetail;
        this.miVwFornitureLogSummary = miVwFornitureLogSummary;
        this.miVwNoteSummary = miVwNoteSummary;
        this.miVwTitolariSummary = miVwTitolariSummary;
        this.miVwComunicazioneSummary = miVwComunicazioneSummary;
        this.miDupFornituraInfo = miDupFornituraInfo;
    }
    

   
    // Property accessors

    public long getIid() {
        return this.iid;
    }
    
    public void setIid(long iid) {
        this.iid = iid;
    }

    public Date getDataCaricamento() {
        return this.dataCaricamento;
    }
    
    public void setDataCaricamento(Date dataCaricamento) {
        this.dataCaricamento = dataCaricamento;
    }

    public String getCodiceFornitura() {
        return this.codiceFornitura;
    }
    
    public void setCodiceFornitura(String codiceFornitura) {
        this.codiceFornitura = codiceFornitura;
    }

    public String getDataIniziale() {
        return this.dataIniziale;
    }
    
    public void setDataIniziale(String dataIniziale) {
        this.dataIniziale = dataIniziale;
    }

    public Date getDataInizialeDate() {
        return this.dataInizialeDate;
    }
    
    public void setDataInizialeDate(Date dataInizialeDate) {
        this.dataInizialeDate = dataInizialeDate;
    }

    public String getDataFinale() {
        return this.dataFinale;
    }
    
    public void setDataFinale(String dataFinale) {
        this.dataFinale = dataFinale;
    }

    public Date getDataFinaleDate() {
        return this.dataFinaleDate;
    }
    
    public void setDataFinaleDate(Date dataFinaleDate) {
        this.dataFinaleDate = dataFinaleDate;
    }

    public String getDataPresAttoRet() {
        return this.dataPresAttoRet;
    }
    
    public void setDataPresAttoRet(String dataPresAttoRet) {
        this.dataPresAttoRet = dataPresAttoRet;
    }

    public String getDataEstrCons() {
        return this.dataEstrCons;
    }
    
    public void setDataEstrCons(String dataEstrCons) {
        this.dataEstrCons = dataEstrCons;
    }

    public String getDataEstrCata() {
        return this.dataEstrCata;
    }
    
    public void setDataEstrCata(String dataEstrCata) {
        this.dataEstrCata = dataEstrCata;
    }

    public String getFileLoadedNotParsed() {
        return this.fileLoadedNotParsed;
    }
    
    public void setFileLoadedNotParsed(String fileLoadedNotParsed) {
        this.fileLoadedNotParsed = fileLoadedNotParsed;
    }

    public String getFileTotNotParsed() {
        return this.fileTotNotParsed;
    }
    
    public void setFileTotNotParsed(String fileTotNotParsed) {
        this.fileTotNotParsed = fileTotNotParsed;
    }

    public Set<MiDupSoggetti> getMiDupSoggettis() {
        return this.miDupSoggettis;
    }
    
    public void setMiDupSoggettis(Set<MiDupSoggetti> miDupSoggettis) {
        this.miDupSoggettis = miDupSoggettis;
    }

    public Set<MiDupFabbricatiIdentifica> getMiDupFabbricatiIdentificas() {
        return this.miDupFabbricatiIdentificas;
    }
    
    public void setMiDupFabbricatiIdentificas(Set<MiDupFabbricatiIdentifica> miDupFabbricatiIdentificas) {
        this.miDupFabbricatiIdentificas = miDupFabbricatiIdentificas;
    }

    public Set<MiDupTerreniInfo> getMiDupTerreniInfos() {
        return this.miDupTerreniInfos;
    }
    
    public void setMiDupTerreniInfos(Set<MiDupTerreniInfo> miDupTerreniInfos) {
        this.miDupTerreniInfos = miDupTerreniInfos;
    }

    public Set<MiDupFabbricatiInfo> getMiDupFabbricatiInfos() {
        return this.miDupFabbricatiInfos;
    }
    
    public void setMiDupFabbricatiInfos(Set<MiDupFabbricatiInfo> miDupFabbricatiInfos) {
        this.miDupFabbricatiInfos = miDupFabbricatiInfos;
    }

    public Set<MiDupIndirizziSog> getMiDupIndirizziSogs() {
        return this.miDupIndirizziSogs;
    }
    
    public void setMiDupIndirizziSogs(Set<MiDupIndirizziSog> miDupIndirizziSogs) {
        this.miDupIndirizziSogs = miDupIndirizziSogs;
    }

    public Set<MiDupTitolarita> getMiDupTitolaritas() {
        return this.miDupTitolaritas;
    }
    
    public void setMiDupTitolaritas(Set<MiDupTitolarita> miDupTitolaritas) {
        this.miDupTitolaritas = miDupTitolaritas;
    }

    public Set<MiDupNotaTras> getMiDupNotaTrases() {
        return this.miDupNotaTrases;
    }
    
    public void setMiDupNotaTrases(Set<MiDupNotaTras> miDupNotaTrases) {
        this.miDupNotaTrases = miDupNotaTrases;
    }

    public Set<MiConsComunicazione> getMiConsComunicaziones() {
        return this.miConsComunicaziones;
    }
    
    public void setMiConsComunicaziones(Set<MiConsComunicazione> miConsComunicaziones) {
        this.miConsComunicaziones = miConsComunicaziones;
    }

    public Set<MiQryFornitureLogDetail> getMiQryFornitureLogDetail() {
        return this.miQryFornitureLogDetail;
    }
    
    public void setMiQryFornitureLogDetail(Set<MiQryFornitureLogDetail> miQryFornitureLogDetail) {
        this.miQryFornitureLogDetail = miQryFornitureLogDetail;
    }

    public MiVwFornitureLogSummary getMiVwFornitureLogSummary() {
        return this.miVwFornitureLogSummary;
    }
    
    public void setMiVwFornitureLogSummary(MiVwFornitureLogSummary miVwFornitureLogSummary) {
        this.miVwFornitureLogSummary = miVwFornitureLogSummary;
    }

    public MiVwNoteSummary getMiVwNoteSummary() {
        return this.miVwNoteSummary;
    }
    
    public void setMiVwNoteSummary(MiVwNoteSummary miVwNoteSummary) {
        this.miVwNoteSummary = miVwNoteSummary;
    }

    public MiVwTitolariSummary getMiVwTitolariSummary() {
        return this.miVwTitolariSummary;
    }
    
    public void setMiVwTitolariSummary(MiVwTitolariSummary miVwTitolariSummary) {
        this.miVwTitolariSummary = miVwTitolariSummary;
    }

    public MiVwComunicazioneSummary getMiVwComunicazioneSummary() {
        return this.miVwComunicazioneSummary;
    }
    
    public void setMiVwComunicazioneSummary(MiVwComunicazioneSummary miVwComunicazioneSummary) {
        this.miVwComunicazioneSummary = miVwComunicazioneSummary;
    }

    public MiDupFornituraInfo getMiDupFornituraInfo() {
        return this.miDupFornituraInfo;
    }
    
    public void setMiDupFornituraInfo(MiDupFornituraInfo miDupFornituraInfo) {
        this.miDupFornituraInfo = miDupFornituraInfo;
    }
   








}
