package it.webred.mui.model;
// Generated 1-apr-2009 13.23.53 by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * MiVwAnagrafe generated by hbm2java
 */

public class MiVwAnagrafe  implements java.io.Serializable {


    // Fields    

     private String codiceFiscale;
     private String tipoSoggetto;
     private String nome;
     private String cognome;
     private String sesso;
     private Date dataNascita;
     private String comuneNascita;
     private String indirizzo;


    // Constructors

    /** default constructor */
    public MiVwAnagrafe() {
    }

	/** minimal constructor */
    public MiVwAnagrafe(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }
    
    /** full constructor */
    public MiVwAnagrafe(String codiceFiscale, String tipoSoggetto, String nome, String cognome, String sesso, Date dataNascita, String comuneNascita, String indirizzo) {
        this.codiceFiscale = codiceFiscale;
        this.tipoSoggetto = tipoSoggetto;
        this.nome = nome;
        this.cognome = cognome;
        this.sesso = sesso;
        this.dataNascita = dataNascita;
        this.comuneNascita = comuneNascita;
        this.indirizzo = indirizzo;
    }
    

   
    // Property accessors

    public String getCodiceFiscale() {
        return this.codiceFiscale;
    }
    
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    public String getTipoSoggetto() {
        return this.tipoSoggetto;
    }
    
    public void setTipoSoggetto(String tipoSoggetto) {
        this.tipoSoggetto = tipoSoggetto;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getSesso() {
        return this.sesso;
    }
    
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    public Date getDataNascita() {
        return this.dataNascita;
    }
    
    public void setDataNascita(Date dataNascita) {
        this.dataNascita = dataNascita;
    }

    public String getComuneNascita() {
        return this.comuneNascita;
    }
    
    public void setComuneNascita(String comuneNascita) {
        this.comuneNascita = comuneNascita;
    }

    public String getIndirizzo() {
        return this.indirizzo;
    }
    
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }
   








}
