package it.webred.mui.model;
// Generated 15-lug-2008 10.19.08 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * MiDupNotaTrasBase generated by hbm2java
 */

public class MiDupNotaTrasBase  implements java.io.Serializable {


    // Fields    

     private long iid;
     private MiDupFornitura miDupFornitura;
     private String idNota;
     private String tipoNota;
     private String numeroNotaTras;
     private long numeroNotaTrasLong;
     private String progressivoNota;
     private String annoNota;
     private Date annoNotaDate;
     private String dataValiditaAtto;
     private Date dataValiditaAttoDate;
     private String dataPresAtto;
     private String esitoNota;
     private String esitoNotaNonReg;
     private String dataRegInAtti;
     private String numeroRepertorio;
     private String flagRettifica;
     private String tipoNotaRet;
     private String numeroNotaRet;
     private String dataPresAttoRet;
     private String cognomeNomeRog;
     private String codFiscRog;
     private String sedeRog;
     private String registrazioneDif;
     private String dataInDif;
     private String codiceAtto;
     private Set<MiDupSoggetti> miDupSoggettis = new HashSet<MiDupSoggetti>(0);
     private Set<MiDupFabbricatiIdentifica> miDupFabbricatiIdentificas = new HashSet<MiDupFabbricatiIdentifica>(0);
     private Set<MiDupTerreniInfo> miDupTerreniInfos = new HashSet<MiDupTerreniInfo>(0);
     private Set<MiDupFabbricatiInfo> miDupFabbricatiInfos = new HashSet<MiDupFabbricatiInfo>(0);
     private Set<MiDupIndirizziSog> miDupIndirizziSogs = new HashSet<MiDupIndirizziSog>(0);
     private Set<MiDupTitolarita> miDupTitolaritas = new HashSet<MiDupTitolarita>(0);
     private Set<MiConsComunicazione> miConsComunicaziones = new HashSet<MiConsComunicazione>(0);
     private Set<MiDupImportLog> miDupImportLogs = new HashSet<MiDupImportLog>(0);


    // Constructors

    /** default constructor */
    public MiDupNotaTrasBase() {
    }

	/** minimal constructor */
    public MiDupNotaTrasBase(MiDupFornitura miDupFornitura) {
        this.miDupFornitura = miDupFornitura;
    }
    
    /** full constructor */
    public MiDupNotaTrasBase(MiDupFornitura miDupFornitura, String idNota, String tipoNota, String numeroNotaTras, long numeroNotaTrasLong, String progressivoNota, String annoNota, Date annoNotaDate, String dataValiditaAtto, Date dataValiditaAttoDate, String dataPresAtto, String esitoNota, String esitoNotaNonReg, String dataRegInAtti, String numeroRepertorio, String flagRettifica, String tipoNotaRet, String numeroNotaRet, String dataPresAttoRet, String cognomeNomeRog, String codFiscRog, String sedeRog, String registrazioneDif, String dataInDif, String codiceAtto, Set<MiDupSoggetti> miDupSoggettis, Set<MiDupFabbricatiIdentifica> miDupFabbricatiIdentificas, Set<MiDupTerreniInfo> miDupTerreniInfos, Set<MiDupFabbricatiInfo> miDupFabbricatiInfos, Set<MiDupIndirizziSog> miDupIndirizziSogs, Set<MiDupTitolarita> miDupTitolaritas, Set<MiConsComunicazione> miConsComunicaziones, Set<MiDupImportLog> miDupImportLogs) {
        this.miDupFornitura = miDupFornitura;
        this.idNota = idNota;
        this.tipoNota = tipoNota;
        this.numeroNotaTras = numeroNotaTras;
        this.numeroNotaTrasLong = numeroNotaTrasLong;
        this.progressivoNota = progressivoNota;
        this.annoNota = annoNota;
        this.annoNotaDate = annoNotaDate;
        this.dataValiditaAtto = dataValiditaAtto;
        this.dataValiditaAttoDate = dataValiditaAttoDate;
        this.dataPresAtto = dataPresAtto;
        this.esitoNota = esitoNota;
        this.esitoNotaNonReg = esitoNotaNonReg;
        this.dataRegInAtti = dataRegInAtti;
        this.numeroRepertorio = numeroRepertorio;
        this.flagRettifica = flagRettifica;
        this.tipoNotaRet = tipoNotaRet;
        this.numeroNotaRet = numeroNotaRet;
        this.dataPresAttoRet = dataPresAttoRet;
        this.cognomeNomeRog = cognomeNomeRog;
        this.codFiscRog = codFiscRog;
        this.sedeRog = sedeRog;
        this.registrazioneDif = registrazioneDif;
        this.dataInDif = dataInDif;
        this.codiceAtto = codiceAtto;
        this.miDupSoggettis = miDupSoggettis;
        this.miDupFabbricatiIdentificas = miDupFabbricatiIdentificas;
        this.miDupTerreniInfos = miDupTerreniInfos;
        this.miDupFabbricatiInfos = miDupFabbricatiInfos;
        this.miDupIndirizziSogs = miDupIndirizziSogs;
        this.miDupTitolaritas = miDupTitolaritas;
        this.miConsComunicaziones = miConsComunicaziones;
        this.miDupImportLogs = miDupImportLogs;
    }
    

   
    // Property accessors

    public long getIid() {
        return this.iid;
    }
    
    public void setIid(long iid) {
        this.iid = iid;
    }

    public MiDupFornitura getMiDupFornitura() {
        return this.miDupFornitura;
    }
    
    public void setMiDupFornitura(MiDupFornitura miDupFornitura) {
        this.miDupFornitura = miDupFornitura;
    }

    public String getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(String idNota) {
        this.idNota = idNota;
    }

    public String getTipoNota() {
        return this.tipoNota;
    }
    
    public void setTipoNota(String tipoNota) {
        this.tipoNota = tipoNota;
    }

    public String getNumeroNotaTras() {
        return this.numeroNotaTras;
    }
    
    public void setNumeroNotaTras(String numeroNotaTras) {
        this.numeroNotaTras = numeroNotaTras;
    }

    public long getNumeroNotaTrasLong() {
        return this.numeroNotaTrasLong;
    }
    
    public void setNumeroNotaTrasLong(long numeroNotaTrasLong) {
        this.numeroNotaTrasLong = numeroNotaTrasLong;
    }

    public String getProgressivoNota() {
        return this.progressivoNota;
    }
    
    public void setProgressivoNota(String progressivoNota) {
        this.progressivoNota = progressivoNota;
    }

    public String getAnnoNota() {
        return this.annoNota;
    }
    
    public void setAnnoNota(String annoNota) {
        this.annoNota = annoNota;
    }

    public Date getAnnoNotaDate() {
        return this.annoNotaDate;
    }
    
    public void setAnnoNotaDate(Date annoNotaDate) {
        this.annoNotaDate = annoNotaDate;
    }

    public String getDataValiditaAtto() {
        return this.dataValiditaAtto;
    }
    
    public void setDataValiditaAtto(String dataValiditaAtto) {
        this.dataValiditaAtto = dataValiditaAtto;
    }

    public Date getDataValiditaAttoDate() {
        return this.dataValiditaAttoDate;
    }
    
    public void setDataValiditaAttoDate(Date dataValiditaAttoDate) {
        this.dataValiditaAttoDate = dataValiditaAttoDate;
    }

    public String getDataPresAtto() {
        return this.dataPresAtto;
    }
    
    public void setDataPresAtto(String dataPresAtto) {
        this.dataPresAtto = dataPresAtto;
    }

    public String getEsitoNota() {
        return this.esitoNota;
    }
    
    public void setEsitoNota(String esitoNota) {
        this.esitoNota = esitoNota;
    }

    public String getEsitoNotaNonReg() {
        return this.esitoNotaNonReg;
    }
    
    public void setEsitoNotaNonReg(String esitoNotaNonReg) {
        this.esitoNotaNonReg = esitoNotaNonReg;
    }

    public String getDataRegInAtti() {
        return this.dataRegInAtti;
    }
    
    public void setDataRegInAtti(String dataRegInAtti) {
        this.dataRegInAtti = dataRegInAtti;
    }

    public String getNumeroRepertorio() {
        return this.numeroRepertorio;
    }
    
    public void setNumeroRepertorio(String numeroRepertorio) {
        this.numeroRepertorio = numeroRepertorio;
    }

    public String getFlagRettifica() {
        return this.flagRettifica;
    }
    
    public void setFlagRettifica(String flagRettifica) {
        this.flagRettifica = flagRettifica;
    }

    public String getTipoNotaRet() {
        return this.tipoNotaRet;
    }
    
    public void setTipoNotaRet(String tipoNotaRet) {
        this.tipoNotaRet = tipoNotaRet;
    }

    public String getNumeroNotaRet() {
        return this.numeroNotaRet;
    }
    
    public void setNumeroNotaRet(String numeroNotaRet) {
        this.numeroNotaRet = numeroNotaRet;
    }

    public String getDataPresAttoRet() {
        return this.dataPresAttoRet;
    }
    
    public void setDataPresAttoRet(String dataPresAttoRet) {
        this.dataPresAttoRet = dataPresAttoRet;
    }

    public String getCognomeNomeRog() {
        return this.cognomeNomeRog;
    }
    
    public void setCognomeNomeRog(String cognomeNomeRog) {
        this.cognomeNomeRog = cognomeNomeRog;
    }

    public String getCodFiscRog() {
        return this.codFiscRog;
    }
    
    public void setCodFiscRog(String codFiscRog) {
        this.codFiscRog = codFiscRog;
    }

    public String getSedeRog() {
        return this.sedeRog;
    }
    
    public void setSedeRog(String sedeRog) {
        this.sedeRog = sedeRog;
    }

    public String getRegistrazioneDif() {
        return this.registrazioneDif;
    }
    
    public void setRegistrazioneDif(String registrazioneDif) {
        this.registrazioneDif = registrazioneDif;
    }

    public String getDataInDif() {
        return this.dataInDif;
    }
    
    public void setDataInDif(String dataInDif) {
        this.dataInDif = dataInDif;
    }

    public String getCodiceAtto() {
		return codiceAtto;
	}

	public void setCodiceAtto(String codiceAtto) {
		this.codiceAtto = codiceAtto;
	}

	public Set<MiDupSoggetti> getMiDupSoggettis() {
        return this.miDupSoggettis;
    }
    
    public void setMiDupSoggettis(Set<MiDupSoggetti> miDupSoggettis) {
        this.miDupSoggettis = miDupSoggettis;
    }

    public Set<MiDupFabbricatiIdentifica> getMiDupFabbricatiIdentificas() {
        return this.miDupFabbricatiIdentificas;
    }
    
    public void setMiDupFabbricatiIdentificas(Set<MiDupFabbricatiIdentifica> miDupFabbricatiIdentificas) {
        this.miDupFabbricatiIdentificas = miDupFabbricatiIdentificas;
    }

    public Set<MiDupTerreniInfo> getMiDupTerreniInfos() {
        return this.miDupTerreniInfos;
    }
    
    public void setMiDupTerreniInfos(Set<MiDupTerreniInfo> miDupTerreniInfos) {
        this.miDupTerreniInfos = miDupTerreniInfos;
    }

    public Set<MiDupFabbricatiInfo> getMiDupFabbricatiInfos() {
        return this.miDupFabbricatiInfos;
    }
    
    public void setMiDupFabbricatiInfos(Set<MiDupFabbricatiInfo> miDupFabbricatiInfos) {
        this.miDupFabbricatiInfos = miDupFabbricatiInfos;
    }

    public Set<MiDupIndirizziSog> getMiDupIndirizziSogs() {
        return this.miDupIndirizziSogs;
    }
    
    public void setMiDupIndirizziSogs(Set<MiDupIndirizziSog> miDupIndirizziSogs) {
        this.miDupIndirizziSogs = miDupIndirizziSogs;
    }

    public Set<MiDupTitolarita> getMiDupTitolaritas() {
        return this.miDupTitolaritas;
    }
    
    public void setMiDupTitolaritas(Set<MiDupTitolarita> miDupTitolaritas) {
        this.miDupTitolaritas = miDupTitolaritas;
    }

    public Set<MiConsComunicazione> getMiConsComunicaziones() {
        return this.miConsComunicaziones;
    }
    
    public void setMiConsComunicaziones(Set<MiConsComunicazione> miConsComunicaziones) {
        this.miConsComunicaziones = miConsComunicaziones;
    }

    public Set<MiDupImportLog> getMiDupImportLogs() {
        return this.miDupImportLogs;
    }
    
    public void setMiDupImportLogs(Set<MiDupImportLog> miDupImportLogs) {
        this.miDupImportLogs = miDupImportLogs;
    }
   








}
