package it.webred.mui.model;
// Generated 15-lug-2008 10.19.13 by Hibernate Tools 3.1.0.beta4



/**
 * MiDupImportLogBase generated by hbm2java
 */

public class MiDupImportLogBase  implements java.io.Serializable {


    // Fields    

     private long iid;
     private MiDupFornitura miDupFornitura;
     private String idNota;
     private MiDupNotaTras miDupNotaTras;
     private Integer tipoRecord;
     private String tabellaRecord;
     private String colonnaRegolaInfranta;
     private CodiceErroreImport codiceRegolaInfranta;
     private MiDupFabbricatiIdentifica miDupFabbricatiIdentifica;
     private MiDupFabbricatiInfo miDupFabbricatiInfo;
     private MiDupFornituraInfo miDupFornituraInfo;
     private MiDupIndirizziSog miDupIndirizziSog;
     private MiDupSoggetti miDupSoggetti;
     private MiDupTerreniInfo miDupTerreniInfo;
     private MiDupTitolarita miDupTitolarita;


    // Constructors

    /** default constructor */
    public MiDupImportLogBase() {
    }

	/** minimal constructor */
    public MiDupImportLogBase(MiDupFornitura miDupFornitura) {
        this.miDupFornitura = miDupFornitura;
    }
    
    /** full constructor */
    public MiDupImportLogBase(MiDupFornitura miDupFornitura, String idNota, MiDupNotaTras miDupNotaTras, Integer tipoRecord, String tabellaRecord, String colonnaRegolaInfranta, CodiceErroreImport codiceRegolaInfranta, MiDupFabbricatiIdentifica miDupFabbricatiIdentifica, MiDupFabbricatiInfo miDupFabbricatiInfo, MiDupFornituraInfo miDupFornituraInfo, MiDupIndirizziSog miDupIndirizziSog, MiDupSoggetti miDupSoggetti, MiDupTerreniInfo miDupTerreniInfo, MiDupTitolarita miDupTitolarita) {
        this.miDupFornitura = miDupFornitura;
        this.idNota = idNota;
        this.miDupNotaTras = miDupNotaTras;
        this.tipoRecord = tipoRecord;
        this.tabellaRecord = tabellaRecord;
        this.colonnaRegolaInfranta = colonnaRegolaInfranta;
        this.codiceRegolaInfranta = codiceRegolaInfranta;
        this.miDupFabbricatiIdentifica = miDupFabbricatiIdentifica;
        this.miDupFabbricatiInfo = miDupFabbricatiInfo;
        this.miDupFornituraInfo = miDupFornituraInfo;
        this.miDupIndirizziSog = miDupIndirizziSog;
        this.miDupSoggetti = miDupSoggetti;
        this.miDupTerreniInfo = miDupTerreniInfo;
        this.miDupTitolarita = miDupTitolarita;
    }
    

   
    // Property accessors

    public long getIid() {
        return this.iid;
    }
    
    public void setIid(long iid) {
        this.iid = iid;
    }

    public MiDupFornitura getMiDupFornitura() {
        return this.miDupFornitura;
    }
    
    public void setMiDupFornitura(MiDupFornitura miDupFornitura) {
        this.miDupFornitura = miDupFornitura;
    }

    public String getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(String idNota) {
        this.idNota = idNota;
    }

    public MiDupNotaTras getMiDupNotaTras() {
        return this.miDupNotaTras;
    }
    
    public void setMiDupNotaTras(MiDupNotaTras miDupNotaTras) {
        this.miDupNotaTras = miDupNotaTras;
    }

    public Integer getTipoRecord() {
        return this.tipoRecord;
    }
    
    public void setTipoRecord(Integer tipoRecord) {
        this.tipoRecord = tipoRecord;
    }

    public String getTabellaRecord() {
        return this.tabellaRecord;
    }
    
    public void setTabellaRecord(String tabellaRecord) {
        this.tabellaRecord = tabellaRecord;
    }

    public String getColonnaRegolaInfranta() {
        return this.colonnaRegolaInfranta;
    }
    
    public void setColonnaRegolaInfranta(String colonnaRegolaInfranta) {
        this.colonnaRegolaInfranta = colonnaRegolaInfranta;
    }

    public CodiceErroreImport getCodiceRegolaInfranta() {
        return this.codiceRegolaInfranta;
    }
    
    public void setCodiceRegolaInfranta(CodiceErroreImport codiceRegolaInfranta) {
        this.codiceRegolaInfranta = codiceRegolaInfranta;
    }

    public MiDupFabbricatiIdentifica getMiDupFabbricatiIdentifica() {
        return this.miDupFabbricatiIdentifica;
    }
    
    public void setMiDupFabbricatiIdentifica(MiDupFabbricatiIdentifica miDupFabbricatiIdentifica) {
        this.miDupFabbricatiIdentifica = miDupFabbricatiIdentifica;
    }

    public MiDupFabbricatiInfo getMiDupFabbricatiInfo() {
        return this.miDupFabbricatiInfo;
    }
    
    public void setMiDupFabbricatiInfo(MiDupFabbricatiInfo miDupFabbricatiInfo) {
        this.miDupFabbricatiInfo = miDupFabbricatiInfo;
    }

    public MiDupFornituraInfo getMiDupFornituraInfo() {
        return this.miDupFornituraInfo;
    }
    
    public void setMiDupFornituraInfo(MiDupFornituraInfo miDupFornituraInfo) {
        this.miDupFornituraInfo = miDupFornituraInfo;
    }

    public MiDupIndirizziSog getMiDupIndirizziSog() {
        return this.miDupIndirizziSog;
    }
    
    public void setMiDupIndirizziSog(MiDupIndirizziSog miDupIndirizziSog) {
        this.miDupIndirizziSog = miDupIndirizziSog;
    }

    public MiDupSoggetti getMiDupSoggetti() {
        return this.miDupSoggetti;
    }
    
    public void setMiDupSoggetti(MiDupSoggetti miDupSoggetti) {
        this.miDupSoggetti = miDupSoggetti;
    }

    public MiDupTerreniInfo getMiDupTerreniInfo() {
        return this.miDupTerreniInfo;
    }
    
    public void setMiDupTerreniInfo(MiDupTerreniInfo miDupTerreniInfo) {
        this.miDupTerreniInfo = miDupTerreniInfo;
    }

    public MiDupTitolarita getMiDupTitolarita() {
        return this.miDupTitolarita;
    }
    
    public void setMiDupTitolarita(MiDupTitolarita miDupTitolarita) {
        this.miDupTitolarita = miDupTitolarita;
    }
   








}
