package it.webred.mui.model;
// Generated 15-lug-2008 10.19.09 by Hibernate Tools 3.1.0.beta4



/**
 * MiVwFornitureLogSummary generated by hbm2java
 */

public class MiVwFornitureLogSummary  implements java.io.Serializable {


    // Fields    

     private long iid_fornitura;
     private long totali;
     private long bloccanti;
     private MiDupFornitura miDupFornitura;


    // Constructors

    /** default constructor */
    public MiVwFornitureLogSummary() {
    }

	/** minimal constructor */
    public MiVwFornitureLogSummary(long iid_fornitura) {
        this.iid_fornitura = iid_fornitura;
    }
    
    /** full constructor */
    public MiVwFornitureLogSummary(long iid_fornitura, long totali, long bloccanti, MiDupFornitura miDupFornitura) {
        this.iid_fornitura = iid_fornitura;
        this.totali = totali;
        this.bloccanti = bloccanti;
        this.miDupFornitura = miDupFornitura;
    }
    

   
    // Property accessors

    public long getIid_fornitura() {
        return this.iid_fornitura;
    }
    
    public void setIid_fornitura(long iid_fornitura) {
        this.iid_fornitura = iid_fornitura;
    }

    public long getTotali() {
        return this.totali;
    }
    
    public void setTotali(long totali) {
        this.totali = totali;
    }

    public long getBloccanti() {
        return this.bloccanti;
    }
    
    public void setBloccanti(long bloccanti) {
        this.bloccanti = bloccanti;
    }

    public MiDupFornitura getMiDupFornitura() {
        return this.miDupFornitura;
    }
    
    public void setMiDupFornitura(MiDupFornitura miDupFornitura) {
        this.miDupFornitura = miDupFornitura;
    }
   








}
