//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 02:08:44 PM CEST 
//


package it.webred.ct.service.jaxb.hetGit.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getImmobiliAccatastatiOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getImmobiliAccatastatiOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baseOutput" type="{}baseOutput" minOccurs="0"/>
 *         &lt;element name="elencoImmobili" type="{}elencoImmobili" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getImmobiliAccatastatiOutput", propOrder = {
    "baseOutput",
    "elencoImmobili"
})
public class GetImmobiliAccatastatiOutput {

    protected BaseOutput baseOutput;
    protected ElencoImmobili elencoImmobili;

    /**
     * Gets the value of the baseOutput property.
     * 
     * @return
     *     possible object is
     *     {@link BaseOutput }
     *     
     */
    public BaseOutput getBaseOutput() {
        return baseOutput;
    }

    /**
     * Sets the value of the baseOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseOutput }
     *     
     */
    public void setBaseOutput(BaseOutput value) {
        this.baseOutput = value;
    }

    /**
     * Gets the value of the elencoImmobili property.
     * 
     * @return
     *     possible object is
     *     {@link ElencoImmobili }
     *     
     */
    public ElencoImmobili getElencoImmobili() {
        return elencoImmobili;
    }

    /**
     * Sets the value of the elencoImmobili property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElencoImmobili }
     *     
     */
    public void setElencoImmobili(ElencoImmobili value) {
        this.elencoImmobili = value;
    }

}
