//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 02:08:44 PM CEST 
//


package it.webred.ct.service.jaxb.hetGit.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hetGit element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="hetGit">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="getImmobiliAccatastatiOutput" type="{}getImmobiliAccatastatiOutput" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getImmobiliAccatastatiOutput"
})
@XmlRootElement(name = "hetGit")
public class HetGit {

    protected GetImmobiliAccatastatiOutput getImmobiliAccatastatiOutput;

    /**
     * Gets the value of the getImmobiliAccatastatiOutput property.
     * 
     * @return
     *     possible object is
     *     {@link GetImmobiliAccatastatiOutput }
     *     
     */
    public GetImmobiliAccatastatiOutput getGetImmobiliAccatastatiOutput() {
        return getImmobiliAccatastatiOutput;
    }

    /**
     * Sets the value of the getImmobiliAccatastatiOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetImmobiliAccatastatiOutput }
     *     
     */
    public void setGetImmobiliAccatastatiOutput(GetImmobiliAccatastatiOutput value) {
        this.getImmobiliAccatastatiOutput = value;
    }

}
