CREATE OR REPLACE VIEW VW_SITICONDUZ_IMM_ALL
(COD_NAZIONALE, FOGLIO, PARTICELLA, SUB, UNIMM, 
 TIPO_TITOLO, PERC_POSS, TIPO_DOCUMENTO, TIT_NO_COD, VALIDO_INIZIO, 
 VALIDO_FINE, ATTO_INIZIO, ATTO_FINE, PK_CUAA, CUAA, 
 DATA_INIZIO, DATA_FINE)
AS 
(
SELECT "COD_NAZIONALE","FOGLIO","PARTICELLA","SUB","UNIMM","TIPO_TITOLO","PERC_POSS","TIPO_DOCUMENTO","TIT_NO_COD","VALIDO_INIZIO","VALIDO_FINE","ATTO_INIZIO","ATTO_FINE","PK_CUAA","CUAA","DATA_INIZIO","DATA_FINE" FROM SITI.SITICONDUZ_IMM_ALL
);


CREATE OR REPLACE VIEW VW_CONTRIBUENTI
(PK_SEQU_CONTRIBUENTI, UK_CODI_CONTRIBUENTE, CODENTE, CODICE_CONTRIBUENTE, CODICE_FISCALE, 
 PARTITA_IVA, DENOMINAZIONE, COGNOME, NOME, SESSO, 
 DATA_NASCITA, DESCR_COMUNE_NASCITA, DESCR_INDIRIZZO, INTERNO, COMUNE_RESIDENZA, 
 FK_CIVICI, FK_ANAGRAFE, FK_COMUNI, DATA_VALIDITA, PROVENIENZA)
AS 
(
SELECT "PK_SEQU_CONTRIBUENTI","UK_CODI_CONTRIBUENTE","CODENTE","CODICE_CONTRIBUENTE","CODICE_FISCALE","PARTITA_IVA","DENOMINAZIONE","COGNOME","NOME","SESSO","DATA_NASCITA","DESCR_COMUNE_NASCITA","DESCR_INDIRIZZO","INTERNO","COMUNE_RESIDENZA","FK_CIVICI","FK_ANAGRAFE","FK_COMUNI","DATA_VALIDITA","PROVENIENZA" FROM DBTOTALE.TRI_CONTRIBUENTI
         WHERE PROVENIENZA = 'T'
);

CREATE OR REPLACE VIEW VW_ANAGRAFE
(TIPO_SOGGETTO, CODICE_FISCALE, COGNOME, NOME, SESSO, 
 DATA_NASCITA, DESCR_COMUNE_NASCITA, DESCR_INDIRIZZO)
AS 
(
 Select ANA.TIPO_SOGGETTO,
        ANA.CODICE_FISCALE,
		ANA.COGNOME,
		ANA.NOME,
		ANA.SESSO,
		ANA.DATA_NASCITA,
		DESCR_COMUNE_NASCITA,
        ANA.SEDIME || ' ' || ANA.NOME_VIA || ' ' || ANA.CIVICO AS DESCR_INDIRIZZO from dbtotale.pop_anagrafe ANA   

);

