package it.escsolution.escwebgis.dup.bean;



/**
 * MiDupFabbricatiInfoId generated by hbm2java
 */
public class DupImmobile  implements java.io.Serializable {

    // MI_DUP_FABBRICATI_INFO    

     private String idFornitura;
     private String idNota;
     private String tipologiaImmobile;
     private String flagGraffato;
     private String idImmobile;
     private String idCatastaleImmobile;
     private String codiceEsito;
     private String naturaImmobile;
     private String zona;
     private String categoria;
     private String classe;
     private String vani;
     private String mc;
     private String mq;
     private String superficie;
     private String renditaEuro;
     private String TLotto;
     private String TEdificio;
     private String TScala;
     private String TInterno1;
     private String TInterno2;
     private String TPiano1;
     private String TPiano2;
     private String TPiano3;
     private String TPiano4;
     private String TToponimo;
     private String TIndirizzo;
     private String TCivico1;
     private String TCivico2;
     private String TCivico3;
     private String CLotto;
     private String CEdificio;
     private String CScala;
     private String CInterno1;
     private String CInterno2;
     private String CPiano1;
     private String CPiano2;
     private String CPiano3;
     private String CPiano4;
     private String CToponimo;
     private String CIndirizzo;
     private String CCivico1;
     private String CCivico2;
     private String CCivico3;
     private String annotazioni;
     
     
     // MI_DUP_FABBRICATI_IDENTIFICA    
     private String sezioneCensuaria;
     private String sezioneUrbana;
     private String foglio;
     private String numero;
     private String denominatore;
     private String subalterno;
     private String edificabilita;
     private String tipoDenuncia;
     private String numeroProtocollo;
     private String anno;
     
 	 private String latitudine;
 	 private String longitudine;
 	 private String codEnte;
     
     private String iid;


    // Constructors

    /** default constructor */
    public DupImmobile() {
    	idFornitura="";
    	idNota="";
    	tipologiaImmobile="";
    	flagGraffato="";
    	idImmobile="";
    	idCatastaleImmobile="";
    	codiceEsito="";
    	naturaImmobile="";
    	zona="";
    	categoria="";
    	classe="";
    	vani="";
    	mc="";
    	mq="";
    	superficie="";
    	renditaEuro="";
    	TLotto="";
    	TEdificio="";
    	TScala="";
    	TInterno1="";
    	TInterno2="";
    	TPiano1="";
    	TPiano2="";
    	TPiano3="";
    	TPiano4="";
    	TToponimo="";
    	TIndirizzo="";
    	TCivico1="";
    	TCivico2="";
    	TCivico3="";
    	CLotto="";
    	CEdificio="";
    	CScala="";
    	CInterno1="";
    	CInterno2="";
    	CPiano1="";
    	CPiano2="";
    	CPiano3="";
    	CPiano4="";
    	CToponimo="";
    	CIndirizzo="";
    	CCivico1="";
    	CCivico2="";
    	CCivico3="";
    	annotazioni="";
    	     
    	     
    	     // MI_DUP_FABBRICATI_IDENTIFICA    
    	sezioneCensuaria="";
    	sezioneUrbana="";
    	foglio="";
    	numero="";
    	denominatore="";
    	subalterno="";
    	edificabilita="";
    	tipoDenuncia="";
    	numeroProtocollo="";
    	anno="";
    }
    
   
    
   
	/**
	 * @return Returns the anno.
	 */
	public String getAnno() {
		return anno;
	}
	/**
	 * @param anno The anno to set.
	 */
	public void setAnno(String anno) {
		this.anno = anno;
	}
	/**
	 * @return Returns the annotazioni.
	 */
	public String getAnnotazioni() {
		return annotazioni;
	}
	/**
	 * @param annotazioni The annotazioni to set.
	 */
	public void setAnnotazioni(String annotazioni) {
		this.annotazioni = annotazioni;
	}
	/**
	 * @return Returns the categoria.
	 */
	public String getCategoria() {
		return categoria;
	}
	/**
	 * @param categoria The categoria to set.
	 */
	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	/**
	 * @return Returns the cCivico1.
	 */
	public String getCCivico1() {
		return CCivico1;
	}
	/**
	 * @param civico1 The cCivico1 to set.
	 */
	public void setCCivico1(String civico1) {
		CCivico1 = civico1;
	}
	/**
	 * @return Returns the cCivico2.
	 */
	public String getCCivico2() {
		return CCivico2;
	}
	/**
	 * @param civico2 The cCivico2 to set.
	 */
	public void setCCivico2(String civico2) {
		CCivico2 = civico2;
	}
	/**
	 * @return Returns the cCivico3.
	 */
	public String getCCivico3() {
		return CCivico3;
	}
	/**
	 * @param civico3 The cCivico3 to set.
	 */
	public void setCCivico3(String civico3) {
		CCivico3 = civico3;
	}
	/**
	 * @return Returns the cEdificio.
	 */
	public String getCEdificio() {
		return CEdificio;
	}
	/**
	 * @param edificio The cEdificio to set.
	 */
	public void setCEdificio(String edificio) {
		CEdificio = edificio;
	}
	/**
	 * @return Returns the cIndirizzo.
	 */
	public String getCIndirizzo() {
		return CIndirizzo;
	}
	/**
	 * @param indirizzo The cIndirizzo to set.
	 */
	public void setCIndirizzo(String indirizzo) {
		CIndirizzo = indirizzo;
	}
	/**
	 * @return Returns the cInterno1.
	 */
	public String getCInterno1() {
		return CInterno1;
	}
	/**
	 * @param interno1 The cInterno1 to set.
	 */
	public void setCInterno1(String interno1) {
		CInterno1 = interno1;
	}
	/**
	 * @return Returns the cInterno2.
	 */
	public String getCInterno2() {
		return CInterno2;
	}
	/**
	 * @param interno2 The cInterno2 to set.
	 */
	public void setCInterno2(String interno2) {
		CInterno2 = interno2;
	}
	/**
	 * @return Returns the classe.
	 */
	public String getClasse() {
		return classe;
	}
	/**
	 * @param classe The classe to set.
	 */
	public void setClasse(String classe) {
		this.classe = classe;
	}
	/**
	 * @return Returns the cLotto.
	 */
	public String getCLotto() {
		return CLotto;
	}
	/**
	 * @param lotto The cLotto to set.
	 */
	public void setCLotto(String lotto) {
		CLotto = lotto;
	}
	/**
	 * @return Returns the codiceEsito.
	 */
	public String getCodiceEsito() {
		return codiceEsito;
	}
	/**
	 * @param codiceEsito The codiceEsito to set.
	 */
	public void setCodiceEsito(String codiceEsito) {
		this.codiceEsito = codiceEsito;
	}
	/**
	 * @return Returns the cPiano1.
	 */
	public String getCPiano1() {
		return CPiano1;
	}
	/**
	 * @param piano1 The cPiano1 to set.
	 */
	public void setCPiano1(String piano1) {
		CPiano1 = piano1;
	}
	/**
	 * @return Returns the cPiano2.
	 */
	public String getCPiano2() {
		return CPiano2;
	}
	/**
	 * @param piano2 The cPiano2 to set.
	 */
	public void setCPiano2(String piano2) {
		CPiano2 = piano2;
	}
	/**
	 * @return Returns the cPiano3.
	 */
	public String getCPiano3() {
		return CPiano3;
	}
	/**
	 * @param piano3 The cPiano3 to set.
	 */
	public void setCPiano3(String piano3) {
		CPiano3 = piano3;
	}
	/**
	 * @return Returns the cPiano4.
	 */
	public String getCPiano4() {
		return CPiano4;
	}
	/**
	 * @param piano4 The cPiano4 to set.
	 */
	public void setCPiano4(String piano4) {
		CPiano4 = piano4;
	}
	/**
	 * @return Returns the cScala.
	 */
	public String getCScala() {
		return CScala;
	}
	/**
	 * @param scala The cScala to set.
	 */
	public void setCScala(String scala) {
		CScala = scala;
	}
	/**
	 * @return Returns the cToponimo.
	 */
	public String getCToponimo() {
		return CToponimo;
	}
	/**
	 * @param toponimo The cToponimo to set.
	 */
	public void setCToponimo(String toponimo) {
		CToponimo = toponimo;
	}
	/**
	 * @return Returns the denominatore.
	 */
	public String getDenominatore() {
		return denominatore;
	}
	/**
	 * @param denominatore The denominatore to set.
	 */
	public void setDenominatore(String denominatore) {
		this.denominatore = denominatore;
	}
	/**
	 * @return Returns the edificabilita.
	 */
	public String getEdificabilita() {
		return edificabilita;
	}
	/**
	 * @param edificabilita The edificabilita to set.
	 */
	public void setEdificabilita(String edificabilita) {
		this.edificabilita = edificabilita;
	}
	/**
	 * @return Returns the flagGraffato.
	 */
	public String getFlagGraffato() {
		return flagGraffato;
	}
	/**
	 * @param flagGraffato The flagGraffato to set.
	 */
	public void setFlagGraffato(String flagGraffato) {
		this.flagGraffato = flagGraffato;
	}
	/**
	 * @return Returns the foglio.
	 */
	public String getFoglio() {
		return foglio;
	}
	/**
	 * @param foglio The foglio to set.
	 */
	public void setFoglio(String foglio) {
		this.foglio = foglio;
	}
	/**
	 * @return Returns the idCatastaleImmobile.
	 */
	public String getIdCatastaleImmobile() {
		return idCatastaleImmobile;
	}
	/**
	 * @param idCatastaleImmobile The idCatastaleImmobile to set.
	 */
	public void setIdCatastaleImmobile(String idCatastaleImmobile) {
		this.idCatastaleImmobile = idCatastaleImmobile;
	}
	/**
	 * @return Returns the idFornitura.
	 */
	public String getIdFornitura() {
		return idFornitura;
	}
	/**
	 * @param idFornitura The idFornitura to set.
	 */
	public void setIdFornitura(String idFornitura) {
		this.idFornitura = idFornitura;
	}
	/**
	 * @return Returns the idImmobile.
	 */
	public String getIdImmobile() {
		return idImmobile;
	}
	/**
	 * @param idImmobile The idImmobile to set.
	 */
	public void setIdImmobile(String idImmobile) {
		this.idImmobile = idImmobile;
	}
	/**
	 * @return Returns the idNota.
	 */
	public String getIdNota() {
		return idNota;
	}
	/**
	 * @param idNota The idNota to set.
	 */
	public void setIdNota(String idNota) {
		this.idNota = idNota;
	}
	/**
	 * @return Returns the mc.
	 */
	public String getMc() {
		return mc;
	}
	/**
	 * @param mc The mc to set.
	 */
	public void setMc(String mc) {
		this.mc = mc;
	}
	/**
	 * @return Returns the mq.
	 */
	public String getMq() {
		return mq;
	}
	/**
	 * @param mq The mq to set.
	 */
	public void setMq(String mq) {
		this.mq = mq;
	}
	/**
	 * @return Returns the naturaImmobile.
	 */
	public String getNaturaImmobile() {
		return naturaImmobile;
	}
	/**
	 * @param naturaImmobile The naturaImmobile to set.
	 */
	public void setNaturaImmobile(String naturaImmobile) {
		this.naturaImmobile = naturaImmobile;
	}
	/**
	 * @return Returns the numero.
	 */
	public String getNumero() {
		return numero;
	}
	/**
	 * @param numero The numero to set.
	 */
	public void setNumero(String numero) {
		this.numero = numero;
	}
	/**
	 * @return Returns the numeroProtocollo.
	 */
	public String getNumeroProtocollo() {
		return numeroProtocollo;
	}
	/**
	 * @param numeroProtocollo The numeroProtocollo to set.
	 */
	public void setNumeroProtocollo(String numeroProtocollo) {
		this.numeroProtocollo = numeroProtocollo;
	}
	/**
	 * @return Returns the renditaEuro.
	 */
	public String getRenditaEuro() {
		return renditaEuro;
	}
	/**
	 * @param renditaEuro The renditaEuro to set.
	 */
	public void setRenditaEuro(String renditaEuro) {
		this.renditaEuro = renditaEuro;
	}
	/**
	 * @return Returns the sezioneCensuaria.
	 */
	public String getSezioneCensuaria() {
		return sezioneCensuaria;
	}
	/**
	 * @param sezioneCensuaria The sezioneCensuaria to set.
	 */
	public void setSezioneCensuaria(String sezioneCensuaria) {
		this.sezioneCensuaria = sezioneCensuaria;
	}
	/**
	 * @return Returns the sezioneUrbana.
	 */
	public String getSezioneUrbana() {
		return sezioneUrbana;
	}
	/**
	 * @param sezioneUrbana The sezioneUrbana to set.
	 */
	public void setSezioneUrbana(String sezioneUrbana) {
		this.sezioneUrbana = sezioneUrbana;
	}
	/**
	 * @return Returns the subalterno.
	 */
	public String getSubalterno() {
		return subalterno;
	}
	/**
	 * @param subalterno The subalterno to set.
	 */
	public void setSubalterno(String subalterno) {
		this.subalterno = subalterno;
	}
	/**
	 * @return Returns the superficie.
	 */
	public String getSuperficie() {
		return superficie;
	}
	/**
	 * @param superficie The superficie to set.
	 */
	public void setSuperficie(String superficie) {
		this.superficie = superficie;
	}
	/**
	 * @return Returns the tCivico1.
	 */
	public String getTCivico1() {
		return TCivico1;
	}
	/**
	 * @param civico1 The tCivico1 to set.
	 */
	public void setTCivico1(String civico1) {
		TCivico1 = civico1;
	}
	/**
	 * @return Returns the tCivico2.
	 */
	public String getTCivico2() {
		return TCivico2;
	}
	/**
	 * @param civico2 The tCivico2 to set.
	 */
	public void setTCivico2(String civico2) {
		TCivico2 = civico2;
	}
	/**
	 * @return Returns the tCivico3.
	 */
	public String getTCivico3() {
		return TCivico3;
	}
	/**
	 * @param civico3 The tCivico3 to set.
	 */
	public void setTCivico3(String civico3) {
		TCivico3 = civico3;
	}
	/**
	 * @return Returns the tEdificio.
	 */
	public String getTEdificio() {
		return TEdificio;
	}
	/**
	 * @param edificio The tEdificio to set.
	 */
	public void setTEdificio(String edificio) {
		TEdificio = edificio;
	}
	/**
	 * @return Returns the tIndirizzo.
	 */
	public String getTIndirizzo() {
		return TIndirizzo;
	}
	/**
	 * @param indirizzo The tIndirizzo to set.
	 */
	public void setTIndirizzo(String indirizzo) {
		TIndirizzo = indirizzo;
	}
	/**
	 * @return Returns the tInterno1.
	 */
	public String getTInterno1() {
		return TInterno1;
	}
	/**
	 * @param interno1 The tInterno1 to set.
	 */
	public void setTInterno1(String interno1) {
		TInterno1 = interno1;
	}
	/**
	 * @return Returns the tInterno2.
	 */
	public String getTInterno2() {
		return TInterno2;
	}
	/**
	 * @param interno2 The tInterno2 to set.
	 */
	public void setTInterno2(String interno2) {
		TInterno2 = interno2;
	}
	/**
	 * @return Returns the tipoDenuncia.
	 */
	public String getTipoDenuncia() {
		return tipoDenuncia;
	}
	/**
	 * @param tipoDenuncia The tipoDenuncia to set.
	 */
	public void setTipoDenuncia(String tipoDenuncia) {
		this.tipoDenuncia = tipoDenuncia;
	}
	/**
	 * @return Returns the tipologiaImmobile.
	 */
	public String getTipologiaImmobile() {
		return tipologiaImmobile;
	}
	/**
	 * @param tipologiaImmobile The tipologiaImmobile to set.
	 */
	public void setTipologiaImmobile(String tipologiaImmobile) {
		this.tipologiaImmobile = tipologiaImmobile;
	}
	/**
	 * @return Returns the tLotto.
	 */
	public String getTLotto() {
		return TLotto;
	}
	/**
	 * @param lotto The tLotto to set.
	 */
	public void setTLotto(String lotto) {
		TLotto = lotto;
	}
	/**
	 * @return Returns the tPiano1.
	 */
	public String getTPiano1() {
		return TPiano1;
	}
	/**
	 * @param piano1 The tPiano1 to set.
	 */
	public void setTPiano1(String piano1) {
		TPiano1 = piano1;
	}
	/**
	 * @return Returns the tPiano2.
	 */
	public String getTPiano2() {
		return TPiano2;
	}
	/**
	 * @param piano2 The tPiano2 to set.
	 */
	public void setTPiano2(String piano2) {
		TPiano2 = piano2;
	}
	/**
	 * @return Returns the tPiano3.
	 */
	public String getTPiano3() {
		return TPiano3;
	}
	/**
	 * @param piano3 The tPiano3 to set.
	 */
	public void setTPiano3(String piano3) {
		TPiano3 = piano3;
	}
	/**
	 * @return Returns the tPiano4.
	 */
	public String getTPiano4() {
		return TPiano4;
	}
	/**
	 * @param piano4 The tPiano4 to set.
	 */
	public void setTPiano4(String piano4) {
		TPiano4 = piano4;
	}
	/**
	 * @return Returns the tScala.
	 */
	public String getTScala() {
		return TScala;
	}
	/**
	 * @param scala The tScala to set.
	 */
	public void setTScala(String scala) {
		TScala = scala;
	}
	/**
	 * @return Returns the tToponimo.
	 */
	public String getTToponimo() {
		return TToponimo;
	}
	/**
	 * @param toponimo The tToponimo to set.
	 */
	public void setTToponimo(String toponimo) {
		TToponimo = toponimo;
	}
	/**
	 * @return Returns the vani.
	 */
	public String getVani() {
		if(!vani.equals("-"))
		{
			double d=new Double(vani).doubleValue();
			d=d*0.1;
			return ""+d; 
		}	
		return vani;
	}
	/**
	 * @param vani The vani to set.
	 */
	public void setVani(String vani) {
		this.vani = vani;
	}
	/**
	 * @return Returns the zona.
	 */
	public String getZona() {
		return zona;
	}
	/**
	 * @param zona The zona to set.
	 */
	public void setZona(String zona) {
		this.zona = zona;
	}

	public String getLatitudine() {
		return latitudine;
	}

	public void setLatitudine(String latitudine) {
		this.latitudine = latitudine;
	}

	public String getLongitudine() {
		return longitudine;
	}

	public void setLongitudine(String longitudine) {
		this.longitudine = longitudine;
	}

	public String getCodEnte() {
		return codEnte;
	}

	public void setCodEnte(String codEnte) {
		this.codEnte = codEnte;
	}




	public String getIid() {
		return iid;
	}




	public void setIid(String iid) {
		this.iid = iid;
	}
}