//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.04 at 03:21:54 PM CET 
//


package it.webred.ct.service.jaxb.intTerritorio.datiCivico.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.webred.ct.service.jaxb.intTerritorio.datiCivico.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.webred.ct.service.jaxb.intTerritorio.datiCivico.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Risposta }
     * 
     */
    public Risposta createRisposta() {
        return new Risposta();
    }

    /**
     * Create an instance of {@link CommonUserInfo }
     * 
     */
    public CommonUserInfo createCommonUserInfo() {
        return new CommonUserInfo();
    }

    /**
     * Create an instance of {@link ParticellaKey }
     * 
     */
    public ParticellaKey createParticellaKey() {
        return new ParticellaKey();
    }

    /**
     * Create an instance of {@link ParticellaInfo }
     * 
     */
    public ParticellaInfo createParticellaInfo() {
        return new ParticellaInfo();
    }

    /**
     * Create an instance of {@link Indirizzo }
     * 
     */
    public Indirizzo createIndirizzo() {
        return new Indirizzo();
    }

    /**
     * Create an instance of {@link InfoVia }
     * 
     */
    public InfoVia createInfoVia() {
        return new InfoVia();
    }

    /**
     * Create an instance of {@link SitLicenzeCommercio }
     * 
     */
    public SitLicenzeCommercio createSitLicenzeCommercio() {
        return new SitLicenzeCommercio();
    }

    /**
     * Create an instance of {@link DatiCivico }
     * 
     */
    public DatiCivico createDatiCivico() {
        return new DatiCivico();
    }

    /**
     * Create an instance of {@link InfoPerCategoria }
     * 
     */
    public InfoPerCategoria createInfoPerCategoria() {
        return new InfoPerCategoria();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

}
